/**
 * cards.js — Medical card database for Buzzword Dash
 *
 * 250 high-yield board-prep cards across all subjects.
 * Each card: id, subj, bw (buzzwords), ans (correct answer),
 * d (distractors), tp (teaching point), ww (why wrong)
 *
 * To add more cards: append objects to the CARDS array.
 * Cards are validated to have exactly 1 correct answer and 2 plausible distractors.
 *
 * Content is original and based on standard board-review concepts.
 * Sources referenced for medical accuracy include StatPearls and
 * standard USMLE/COMLEX review frameworks.
 */

export const SUBJECTS = [
  "Neurology", "Cardiology", "Nephrology", "Psychiatry",
  "Gastroenterology", "Pulmonology", "Infectious Disease",
  "Endocrinology", "Hematology/Oncology", "Rheumatology",
  "Obstetrics/Gynecology", "Pediatrics", "Surgery",
  "Emergency Medicine", "Multisystem / Mixed"
];

export const CARDS = [

  // ╔══════════════════════════════════════════════════╗
  // ║              NEUROLOGY (1-50)                    ║
  // ╚══════════════════════════════════════════════════╝

  {id:"n001",subj:"Neurology",bw:["Thunderclap headache","Worst headache of life"],ans:"Subarachnoid Hemorrhage",d:["Migraine","Tension Headache"],tp:"SAH: thunderclap headache until proven otherwise. CT head then LP if CT negative.",ww:{"Migraine":"Gradual onset with aura/nausea.","Tension Headache":"Bilateral band-like, mild-moderate."}},
  {id:"n002",subj:"Neurology",bw:["Sudden hemiparesis","Eyes deviate toward lesion"],ans:"MCA Stroke",d:["ACA Stroke","Posterior Stroke"],tp:"Cortical hemispheric lesions cause gaze deviation toward the lesion side.",ww:{"ACA Stroke":"Leg-predominant weakness.","Posterior Stroke":"Vertigo, ataxia, visual field cuts."}},
  {id:"n003",subj:"Neurology",bw:["Resting tremor","Bradykinesia","Cogwheel rigidity"],ans:"Parkinson Disease",d:["Essential Tremor","Huntington Disease"],tp:"Parkinson: substantia nigra dopamine neuron loss. Lewy bodies on histology.",ww:{"Essential Tremor":"Action tremor, improves with alcohol.","Huntington Disease":"Chorea, caudate atrophy, CAG repeats."}},
  {id:"n004",subj:"Neurology",bw:["Young woman","Painful vision loss","RAPD"],ans:"Optic Neuritis (MS)",d:["Retinal Detachment","Acute Glaucoma"],tp:"Optic neuritis: painful unilateral vision loss with RAPD. Strongly associated with MS.",ww:{"Retinal Detachment":"Painless with floaters/curtain.","Acute Glaucoma":"Red eye, halos, fixed mid-dilated pupil."}},
  {id:"n005",subj:"Neurology",bw:["Ascending paralysis","Post-URI","Albuminocytologic dissociation"],ans:"Guillain-Barré Syndrome",d:["Botulism","Transverse Myelitis"],tp:"GBS: ascending demyelinating polyneuropathy. High CSF protein with few cells.",ww:{"Botulism":"Descending paralysis.","Transverse Myelitis":"Spinal cord level, bilateral."}},
  {id:"n006",subj:"Neurology",bw:["Descending paralysis","Diplopia","Canned food"],ans:"Botulism",d:["Guillain-Barré Syndrome","Myasthenia Gravis"],tp:"Botulism: descending flaccid paralysis. Blocks presynaptic ACh release at NMJ.",ww:{"Guillain-Barré Syndrome":"Ascending paralysis.","Myasthenia Gravis":"Fatigable weakness that improves with rest."}},
  {id:"n007",subj:"Neurology",bw:["Ptosis worse with use","Thymoma","Anti-AChR antibodies"],ans:"Myasthenia Gravis",d:["Lambert-Eaton Syndrome","Botulism"],tp:"MG: post-synaptic anti-AChR antibodies. Fatigable weakness. Thymoma association.",ww:{"Lambert-Eaton Syndrome":"Presynaptic anti-VGCC. Improves with use.","Botulism":"Descending paralysis, food exposure."}},
  {id:"n008",subj:"Neurology",bw:["Proximal weakness improves with use","Small cell lung cancer"],ans:"Lambert-Eaton Syndrome",d:["Myasthenia Gravis","Polymyositis"],tp:"Lambert-Eaton: presynaptic anti-VGCC antibodies. Paraneoplastic with SCLC.",ww:{"Myasthenia Gravis":"Weakness worsens with use.","Polymyositis":"No cancer association typically, elevated CK."}},
  {id:"n009",subj:"Neurology",bw:["Lip smacking","Automatisms","Temporal lobe"],ans:"Focal Seizure with Impaired Awareness",d:["Absence Seizure","Tonic-Clonic Seizure"],tp:"Complex partial (focal with impaired awareness) from temporal lobe with automatisms.",ww:{"Absence Seizure":"Brief staring, 3Hz spike-wave, children.","Tonic-Clonic Seizure":"Bilateral stiffening then rhythmic jerking."}},
  {id:"n010",subj:"Neurology",bw:["Child","Absence seizures","3 Hz spike-and-wave"],ans:"Childhood Absence Epilepsy",d:["Focal Seizure","Juvenile Myoclonic Epilepsy"],tp:"Absence: brief staring episodes, 3Hz generalized spike-wave. Ethosuximide first-line.",ww:{"Focal Seizure":"Aura, automatisms, post-ictal confusion.","Juvenile Myoclonic Epilepsy":"Morning myoclonic jerks, 4-6Hz polyspike."}},
  {id:"n011",subj:"Neurology",bw:["Fever","Temporal lobe lesion","HSV"],ans:"HSV Encephalitis",d:["Bacterial Meningitis","Toxoplasmosis"],tp:"HSV-1: most common sporadic viral encephalitis. Temporal lobe. IV acyclovir.",ww:{"Bacterial Meningitis":"Diffuse meningeal, not focal temporal.","Toxoplasmosis":"Ring-enhancing in HIV, basal ganglia."}},
  {id:"n012",subj:"Neurology",bw:["Bilateral INO","Young woman"],ans:"Multiple Sclerosis",d:["Brainstem Stroke","Myasthenia Gravis"],tp:"Bilateral internuclear ophthalmoplegia in a young patient is classic for MS.",ww:{"Brainstem Stroke":"Unilateral INO more common, older patient.","Myasthenia Gravis":"Fatigable ptosis, not INO."}},
  {id:"n013",subj:"Neurology",bw:["Electric shock down spine with neck flexion"],ans:"Lhermitte Sign (MS)",d:["Cervical Spondylosis","Meningitis"],tp:"Lhermitte sign: posterior column demyelination, classic in MS.",ww:{"Cervical Spondylosis":"Gradual myelopathy.","Meningitis":"Neck stiffness, fever, not electric shock."}},
  {id:"n014",subj:"Neurology",bw:["Intention tremor","Scanning speech","Nystagmus"],ans:"Cerebellar Lesion",d:["Parkinson Disease","Essential Tremor"],tp:"Cerebellar triad: intention tremor, scanning speech, nystagmus. Think DANISH mnemonic.",ww:{"Parkinson Disease":"Resting tremor, not intention.","Essential Tremor":"Action tremor without nystagmus/dysarthria."}},
  {id:"n015",subj:"Neurology",bw:["Foot drop","Common peroneal nerve"],ans:"Peroneal Nerve Palsy",d:["L5 Radiculopathy","Sciatic Nerve Injury"],tp:"Common peroneal nerve at fibular head — foot drop, sensory loss lateral leg.",ww:{"L5 Radiculopathy":"Back pain radiating, positive SLR.","Sciatic Nerve Injury":"Broader deficit including hamstrings."}},
  {id:"n016",subj:"Neurology",bw:["Wrist drop","Saturday night palsy"],ans:"Radial Nerve Palsy",d:["Ulnar Nerve Palsy","Median Nerve Injury"],tp:"Radial nerve compressed at spiral groove of humerus — wrist drop, finger drop.",ww:{"Ulnar Nerve Palsy":"Claw hand, loss of finger abduction.","Median Nerve Injury":"Ape hand, thenar atrophy."}},
  {id:"n017",subj:"Neurology",bw:["Elderly","Stepwise cognitive decline","Focal deficits"],ans:"Vascular Dementia",d:["Alzheimer Disease","Lewy Body Dementia"],tp:"Vascular dementia: stepwise decline tied to cerebrovascular events.",ww:{"Alzheimer Disease":"Gradual progressive memory loss.","Lewy Body Dementia":"Visual hallucinations, parkinsonism."}},
  {id:"n018",subj:"Neurology",bw:["Progressive memory loss","Hippocampal atrophy","Neurofibrillary tangles"],ans:"Alzheimer Disease",d:["Vascular Dementia","Frontotemporal Dementia"],tp:"Alzheimer: amyloid plaques + neurofibrillary tangles (tau). ACh deficit.",ww:{"Vascular Dementia":"Stepwise decline.","Frontotemporal Dementia":"Personality changes, Pick bodies."}},
  {id:"n019",subj:"Neurology",bw:["Personality change","Disinhibition","Pick bodies"],ans:"Frontotemporal Dementia",d:["Alzheimer Disease","Normal Pressure Hydrocephalus"],tp:"FTD: frontal/temporal atrophy, behavior changes early. Pick bodies on histology.",ww:{"Alzheimer Disease":"Memory loss predominates.","Normal Pressure Hydrocephalus":"Wet, wacky, wobbly triad."}},
  {id:"n020",subj:"Neurology",bw:["Visual hallucinations","Elderly","Fluctuating cognition","Parkinsonism"],ans:"Lewy Body Dementia",d:["Alzheimer Disease","Delirium"],tp:"LBD: visual hallucinations, parkinsonism, fluctuating cognition. AVOID antipsychotics.",ww:{"Alzheimer Disease":"No early visual hallucinations.","Delirium":"Acute, identifiable cause."}},
  {id:"n021",subj:"Neurology",bw:["Rapidly progressive dementia","Myoclonus","Periodic sharp waves EEG"],ans:"Creutzfeldt-Jakob Disease",d:["Alzheimer Disease","Viral Encephalitis"],tp:"CJD: prion disease, rapid dementia, myoclonus. 14-3-3 protein in CSF.",ww:{"Alzheimer Disease":"Slow progressive.","Viral Encephalitis":"Fever, focal findings."}},
  {id:"n022",subj:"Neurology",bw:["Ophthalmoplegia","Ataxia","Confusion","Alcoholism"],ans:"Wernicke Encephalopathy",d:["Korsakoff Syndrome","Hepatic Encephalopathy"],tp:"Wernicke: thiamine (B1) deficiency triad. Give thiamine BEFORE glucose.",ww:{"Korsakoff Syndrome":"Confabulation, irreversible.","Hepatic Encephalopathy":"Asterixis, elevated ammonia."}},
  {id:"n023",subj:"Neurology",bw:["Confabulation","Anterograde amnesia","Mammillary body damage"],ans:"Korsakoff Syndrome",d:["Wernicke Encephalopathy","Delirium"],tp:"Korsakoff: chronic thiamine deficiency, irreversible. Mammillary body necrosis.",ww:{"Wernicke Encephalopathy":"Acute, reversible with thiamine.","Delirium":"Fluctuating, identifiable cause."}},
  {id:"n024",subj:"Neurology",bw:["Chorea","Psychiatric symptoms","Caudate atrophy","CAG repeats"],ans:"Huntington Disease",d:["Sydenham Chorea","Wilson Disease"],tp:"Huntington: autosomal dominant, chromosome 4, CAG trinucleotide repeat expansion.",ww:{"Sydenham Chorea":"Post-streptococcal, children, self-limited.","Wilson Disease":"Kayser-Fleischer rings, copper."}},
  {id:"n025",subj:"Neurology",bw:["Unilateral headache","Lacrimation","Rhinorrhea","Orbital"],ans:"Cluster Headache",d:["Migraine","Trigeminal Neuralgia"],tp:"Cluster: severe unilateral periorbital, autonomic symptoms. Male predominance.",ww:{"Migraine":"Gradual, photophobia, aura.","Trigeminal Neuralgia":"Electric shock in V2/V3."}},
  {id:"n026",subj:"Neurology",bw:["Unilateral facial paralysis","Forehead involved","Cannot close eye"],ans:"Bell Palsy",d:["Stroke","Ramsay Hunt Syndrome"],tp:"Bell palsy: LMN CN VII, entire half of face. Usually idiopathic.",ww:{"Stroke":"UMN pattern spares forehead.","Ramsay Hunt Syndrome":"Vesicular rash in ear (VZV)."}},
  {id:"n027",subj:"Neurology",bw:["Bitemporal hemianopia","Pituitary mass"],ans:"Pituitary Adenoma",d:["Craniopharyngioma","Optic Glioma"],tp:"Chiasmal compression: bitemporal hemianopia. Pituitary adenoma most common cause.",ww:{"Craniopharyngioma":"Child, calcified, suprasellar.","Optic Glioma":"NF1 association."}},
  {id:"n028",subj:"Neurology",bw:["Contralateral homonymous hemianopia","No motor deficit"],ans:"PCA Stroke",d:["MCA Stroke","Optic Neuritis"],tp:"PCA supplies visual cortex. Isolated visual field cut without motor deficit.",ww:{"MCA Stroke":"Motor/sensory deficit, aphasia.","Optic Neuritis":"Monocular, painful."}},
  {id:"n029",subj:"Neurology",bw:["Ipsilateral Horner","Contralateral pain/temp loss","Dysphagia"],ans:"Wallenberg Syndrome",d:["Medial Medullary Syndrome","Cerebellar Stroke"],tp:"Wallenberg (lateral medullary): PICA occlusion. Crossed findings.",ww:{"Medial Medullary Syndrome":"Contralateral hemiparesis, tongue deviation.","Cerebellar Stroke":"Ataxia without crossed findings."}},
  {id:"n030",subj:"Neurology",bw:["Loss of pain/temp","Cape distribution","Preserved proprioception"],ans:"Syringomyelia",d:["Multiple Sclerosis","Brown-Séquard"],tp:"Syringomyelia: central cord cavitation crossing anterior commissure.",ww:{"Multiple Sclerosis":"Multiple lesions, white matter.","Brown-Séquard":"Hemisection pattern."}},
  {id:"n031",subj:"Neurology",bw:["Fasciculations","Tongue atrophy","UMN and LMN signs"],ans:"ALS",d:["Cervical Myelopathy","Multiple Sclerosis"],tp:"ALS: combined UMN+LMN without sensory loss. Tongue fasciculations.",ww:{"Cervical Myelopathy":"Sensory changes present.","Multiple Sclerosis":"Sensory symptoms, relapsing-remitting."}},
  {id:"n032",subj:"Neurology",bw:["Saddle anesthesia","Urinary retention","Bilateral leg pain"],ans:"Cauda Equina Syndrome",d:["Conus Medullaris Syndrome","Lumbar Disc Herniation"],tp:"CES: surgical emergency, LMN signs, saddle anesthesia, areflexia.",ww:{"Conus Medullaris Syndrome":"UMN+LMN mixed, early bladder.","Lumbar Disc Herniation":"Unilateral radiculopathy."}},
  {id:"n033",subj:"Neurology",bw:["Headache","Papilledema","Obese young woman"],ans:"Idiopathic Intracranial Hypertension",d:["Brain Tumor","Venous Sinus Thrombosis"],tp:"IIH: elevated ICP without mass. Obesity, tetracyclines, vitamin A.",ww:{"Brain Tumor":"Focal deficits, mass on imaging.","Venous Sinus Thrombosis":"Hypercoagulable, MRV diagnostic."}},
  {id:"n034",subj:"Neurology",bw:["Subacute combined degeneration","B12 deficiency"],ans:"Vitamin B12 Deficiency Myelopathy",d:["Multiple Sclerosis","Tabes Dorsalis"],tp:"B12 deficiency: demyelination of dorsal columns and lateral corticospinal tracts.",ww:{"Multiple Sclerosis":"Younger, relapsing-remitting.","Tabes Dorsalis":"Tertiary syphilis, lightning pains."}},

  // ╔══════════════════════════════════════════════════╗
  // ║              CARDIOLOGY (35-68)                  ║
  // ╚══════════════════════════════════════════════════╝

  {id:"c001",subj:"Cardiology",bw:["Fever","Murmur","Janeway lesions"],ans:"Infective Endocarditis",d:["Rheumatic Fever","Atrial Myxoma"],tp:"IE: Janeway (painless palms/soles), Osler (painful), Roth spots, splinter hemorrhages.",ww:{"Rheumatic Fever":"Jones criteria, migratory polyarthritis.","Atrial Myxoma":"Positional dyspnea, tumor plop."}},
  {id:"c002",subj:"Cardiology",bw:["Pulsus paradoxus","JVD","Muffled heart sounds"],ans:"Cardiac Tamponade",d:["Tension Pneumothorax","Constrictive Pericarditis"],tp:"Beck's triad. Pulsus paradoxus >10mmHg SBP drop with inspiration.",ww:{"Tension Pneumothorax":"Tracheal deviation, absent breath sounds.","Constrictive Pericarditis":"Kussmaul sign, calcified pericardium."}},
  {id:"c003",subj:"Cardiology",bw:["Marfan","Tearing chest pain","BP differential"],ans:"Aortic Dissection",d:["STEMI","Pulmonary Embolism"],tp:"Aortic dissection: sudden tearing pain to back. Stanford Type A = ascending, Type B = descending. CXR: widened mediastinum.",ww:{"STEMI":"Crushing substernal, ST elevation.","Pulmonary Embolism":"Acute dyspnea, pleuritic pain."}},
  {id:"c004",subj:"Cardiology",bw:["Irregularly irregular","No P waves"],ans:"Atrial Fibrillation",d:["Atrial Flutter","SVT"],tp:"AFib: irregularly irregular, absent P waves. CHA₂DS₂-VASc for anticoagulation.",ww:{"Atrial Flutter":"Regular sawtooth pattern.","SVT":"Regular narrow complex."}},
  {id:"c005",subj:"Cardiology",bw:["Sawtooth pattern","Regular","150 bpm"],ans:"Atrial Flutter",d:["Atrial Fibrillation","Sinus Tachycardia"],tp:"Flutter: sawtooth P waves, 2:1 block gives rate ~150.",ww:{"Atrial Fibrillation":"Irregularly irregular, no P waves.","Sinus Tachycardia":"Normal P waves before each QRS."}},
  {id:"c006",subj:"Cardiology",bw:["Young athlete","Sudden cardiac death","Septal hypertrophy"],ans:"Hypertrophic Cardiomyopathy",d:["Dilated Cardiomyopathy","Aortic Stenosis"],tp:"HCM: dynamic LVOT obstruction. Worse with Valsalva/standing (decreased preload).",ww:{"Dilated Cardiomyopathy":"Four-chamber dilation.","Aortic Stenosis":"Fixed obstruction."}},
  {id:"c007",subj:"Cardiology",bw:["Crescendo-decrescendo murmur","Syncope","Angina"],ans:"Aortic Stenosis",d:["Mitral Regurgitation","HCM"],tp:"AS: triad of angina, syncope, heart failure. Pulsus parvus et tardus.",ww:{"Mitral Regurgitation":"Holosystolic at apex.","HCM":"Dynamic obstruction, young patient."}},
  {id:"c008",subj:"Cardiology",bw:["Holosystolic murmur","Radiates to axilla"],ans:"Mitral Regurgitation",d:["Aortic Stenosis","Tricuspid Regurgitation"],tp:"MR: holosystolic at apex, radiates to axilla. Causes: MVP, rheumatic, ischemic.",ww:{"Aortic Stenosis":"Crescendo-decrescendo to carotids.","Tricuspid Regurgitation":"Holosystolic at LLSB, JVD."}},
  {id:"c009",subj:"Cardiology",bw:["Mid-systolic click","Murmur louder with Valsalva"],ans:"Mitral Valve Prolapse",d:["Mitral Stenosis","HCM"],tp:"MVP: click earlier and murmur louder with decreased preload.",ww:{"Mitral Stenosis":"Opening snap, diastolic rumble.","HCM":"No click, dynamic obstruction."}},
  {id:"c010",subj:"Cardiology",bw:["Opening snap","Diastolic rumble","Rheumatic history"],ans:"Mitral Stenosis",d:["Mitral Regurgitation","Aortic Regurgitation"],tp:"MS: rheumatic most common cause. Fish-mouth orifice. Can cause AFib.",ww:{"Mitral Regurgitation":"Holosystolic, not diastolic.","Aortic Regurgitation":"Early diastolic blowing."}},
  {id:"c011",subj:"Cardiology",bw:["Wide pulse pressure","Bounding pulses","Early diastolic murmur"],ans:"Aortic Regurgitation",d:["Aortic Stenosis","PDA"],tp:"AR: water-hammer pulse, wide pulse pressure, Austin Flint murmur.",ww:{"Aortic Stenosis":"Narrow pulse pressure.","PDA":"Continuous machinery murmur."}},
  {id:"c012",subj:"Cardiology",bw:["Chest pain","ST elevation","Troponin rise"],ans:"STEMI",d:["Pericarditis","Aortic Dissection"],tp:"STEMI: emergent PCI within 90min or fibrinolytics within 30min.",ww:{"Pericarditis":"Diffuse ST elevation, pleuritic.","Aortic Dissection":"Tearing to back, BP differential."}},
  {id:"c013",subj:"Cardiology",bw:["Diffuse ST elevation","Pleuritic pain","Friction rub"],ans:"Pericarditis",d:["STEMI","Myocarditis"],tp:"Pericarditis: diffuse ST elevation with PR depression. NSAIDs + colchicine.",ww:{"STEMI":"Regional ST elevation, reciprocal changes.","Myocarditis":"Post-viral, troponin rise."}},
  {id:"c014",subj:"Cardiology",bw:["Delta wave","Short PR","Wide QRS"],ans:"Wolff-Parkinson-White",d:["LBBB","Ventricular Tachycardia"],tp:"WPW: accessory pathway (Bundle of Kent). Avoid AV nodal blockers in WPW+AFib.",ww:{"LBBB":"No delta wave, normal PR.","Ventricular Tachycardia":"No delta wave, usually regular."}},
  {id:"c015",subj:"Cardiology",bw:["Long QT","Torsades de pointes"],ans:"Long QT Syndrome",d:["Ventricular Fibrillation","Brugada Syndrome"],tp:"Long QT: risk of TdP. Treat TdP with IV magnesium.",ww:{"Ventricular Fibrillation":"Chaotic, no organized QRS.","Brugada Syndrome":"Pseudo-RBBB, coved ST V1-V3."}},
  {id:"c016",subj:"Cardiology",bw:["Newborn","Cyanosis","Boot-shaped heart"],ans:"Tetralogy of Fallot",d:["Transposition of Great Arteries","Coarctation"],tp:"TOF: VSD, overriding aorta, pulmonary stenosis, RVH. Tet spells relieved by squatting.",ww:{"Transposition of Great Arteries":"Egg-on-string, parallel circuits.","Coarctation":"Upper extremity HTN, not cyanotic."}},
  {id:"c017",subj:"Cardiology",bw:["Egg-on-a-string","Cyanosis at birth","Parallel circulations"],ans:"Transposition of Great Arteries",d:["Tetralogy of Fallot","Total Anomalous Pulmonary Venous Return"],tp:"TGA: aorta from RV, PA from LV. PGE1 + balloon septostomy.",ww:{"Tetralogy of Fallot":"Boot-shaped heart, tet spells.","Total Anomalous Pulmonary Venous Return":"Snowman sign."}},
  {id:"c018",subj:"Cardiology",bw:["Continuous machinery murmur","Bounding pulses"],ans:"Patent Ductus Arteriosus",d:["ASD","VSD"],tp:"PDA: failure of ductus closure. Indomethacin to close. PGE1 to keep open.",ww:{"ASD":"Fixed split S2.","VSD":"Holosystolic at LLSB."}},
  {id:"c019",subj:"Cardiology",bw:["Fixed split S2","Systolic murmur"],ans:"Atrial Septal Defect",d:["VSD","PDA"],tp:"ASD: fixed split S2 due to persistent L-to-R shunt.",ww:{"VSD":"Holosystolic, no fixed split S2.","PDA":"Continuous machinery murmur."}},
  {id:"c020",subj:"Cardiology",bw:["Coarctation","Rib notching","Upper extremity HTN"],ans:"Coarctation of Aorta",d:["Aortic Stenosis","PDA"],tp:"Coarctation at ligamentum arteriosum. Turner syndrome, bicuspid AV.",ww:{"Aortic Stenosis":"No BP differential.","PDA":"Continuous murmur."}},
  {id:"c021",subj:"Cardiology",bw:["S3 gallop","Bibasilar crackles","Peripheral edema"],ans:"Congestive Heart Failure",d:["Pneumonia","Nephrotic Syndrome"],tp:"CHF: S3 = volume overload, elevated BNP.",ww:{"Pneumonia":"Fever, focal consolidation.","Nephrotic Syndrome":"Proteinuria >3.5g."}},
  {id:"c022",subj:"Cardiology",bw:["Postpartum","Dilated cardiomyopathy","New-onset HF"],ans:"Peripartum Cardiomyopathy",d:["Takotsubo Cardiomyopathy","HCM"],tp:"Peripartum CMP: last month pregnancy to 5mo postpartum.",ww:{"Takotsubo Cardiomyopathy":"Emotional stress, apical ballooning.","HCM":"Septal hypertrophy."}},
  {id:"c023",subj:"Cardiology",bw:["Electrical alternans","Low voltage QRS","Large effusion"],ans:"Cardiac Tamponade (ECG findings)",d:["Pericarditis","Myocarditis"],tp:"Electrical alternans: swinging heart in large effusion.",ww:{"Pericarditis":"Normal voltage, diffuse ST elevation.","Myocarditis":"No electrical alternans."}},

  // ╔══════════════════════════════════════════════════╗
  // ║             NEPHROLOGY (69-92)                   ║
  // ╚══════════════════════════════════════════════════╝

  {id:"ne001",subj:"Nephrology",bw:["Child","Periorbital edema","Hypoalbuminemia"],ans:"Minimal Change Disease",d:["Membranous Nephropathy","FSGS"],tp:"MCD: most common nephrotic in children. Normal LM, foot process effacement EM.",ww:{"Membranous Nephropathy":"Adults, thick GBM, anti-PLA2R.","FSGS":"Most common nephrotic in African Americans."}},
  {id:"ne002",subj:"Nephrology",bw:["Peaked T waves","Widened QRS"],ans:"Hyperkalemia",d:["Hypocalcemia","Hypomagnesemia"],tp:"Hyperkalemia ECG: peaked T → widened QRS → sine wave → arrest. Calcium gluconate first.",ww:{"Hypocalcemia":"Prolonged QT, Chvostek/Trousseau.","Hypomagnesemia":"Refractory hypoK and hypoCa."}},
  {id:"ne003",subj:"Nephrology",bw:["Muddy brown casts","Elevated creatinine","Post-surgery"],ans:"Acute Tubular Necrosis",d:["Prerenal Azotemia","Glomerulonephritis"],tp:"ATN: muddy brown granular casts. FeNa >2%. Most common intrinsic AKI.",ww:{"Prerenal Azotemia":"FeNa <1%, BUN/Cr >20.","Glomerulonephritis":"RBC casts."}},
  {id:"ne004",subj:"Nephrology",bw:["RBC casts","Hematuria","Proteinuria"],ans:"Nephritic Syndrome",d:["Nephrotic Syndrome","UTI"],tp:"Nephritic: RBC casts pathognomonic. HTN, oliguria, mild proteinuria.",ww:{"Nephrotic Syndrome":">3.5g proteinuria, edema, lipiduria.","UTI":"WBCs, bacteria."}},
  {id:"ne005",subj:"Nephrology",bw:["Post-streptococcal","Cola-colored urine","Child"],ans:"Post-Streptococcal GN",d:["IgA Nephropathy","Membranoproliferative GN"],tp:"PSGN: 2-3 weeks post-GAS pharyngitis. Low C3, subepithelial humps on EM.",ww:{"IgA Nephropathy":"Concurrent with URI (synpharyngitic).","Membranoproliferative GN":"Tram-track GBM splitting."}},
  {id:"ne006",subj:"Nephrology",bw:["Hematuria concurrent with URI","IgA deposits"],ans:"IgA Nephropathy",d:["PSGN","Thin Basement Membrane Disease"],tp:"IgA (Berger): most common GN worldwide. Synpharyngitic hematuria.",ww:{"PSGN":"Delayed 2-3 weeks, low C3.","Thin Basement Membrane Disease":"Benign familial hematuria."}},
  {id:"ne007",subj:"Nephrology",bw:["Hemoptysis","Hematuria","Anti-GBM antibodies"],ans:"Goodpasture Syndrome",d:["Granulomatosis with Polyangiitis","SLE Nephritis"],tp:"Goodpasture: anti-GBM, pulmonary-renal syndrome. Linear IF pattern.",ww:{"Granulomatosis with Polyangiitis":"c-ANCA, granulomatous.","SLE Nephritis":"ANA, anti-dsDNA."}},
  {id:"ne008",subj:"Nephrology",bw:["Hemoptysis","Hematuria","c-ANCA","Granulomas"],ans:"Granulomatosis with Polyangiitis",d:["Goodpasture Syndrome","Microscopic Polyangiitis"],tp:"GPA (Wegener): c-ANCA (anti-PR3), upper/lower airway + renal.",ww:{"Goodpasture Syndrome":"Anti-GBM, linear IF.","Microscopic Polyangiitis":"p-ANCA, no granulomas."}},
  {id:"ne009",subj:"Nephrology",bw:["Spike-and-dome on EM","Adult nephrotic","Anti-PLA2R"],ans:"Membranous Nephropathy",d:["Minimal Change Disease","FSGS"],tp:"Membranous: most common primary nephrotic in white adults. Subepithelial deposits.",ww:{"Minimal Change Disease":"Children, steroid responsive.","FSGS":"Segmental sclerosis."}},
  {id:"ne010",subj:"Nephrology",bw:["BUN/Cr >20","FeNa <1%","Concentrated urine"],ans:"Prerenal Azotemia",d:["ATN","Post-renal Obstruction"],tp:"Prerenal: kidney responds to hypoperfusion. Correct volume first.",ww:{"ATN":"FeNa >2%, isosthenuria.","Post-renal Obstruction":"Hydronephrosis on imaging."}},
  {id:"ne011",subj:"Nephrology",bw:["Non-anion gap acidosis","Low K+","Cannot acidify urine"],ans:"Type 1 RTA (Distal)",d:["Type 2 RTA","Type 4 RTA"],tp:"Type 1 distal: urine pH >5.3. HypoK. Stones, nephrocalcinosis.",ww:{"Type 2 RTA":"Proximal bicarb wasting, Fanconi.","Type 4 RTA":"HyperK, aldosterone deficiency."}},
  {id:"ne012",subj:"Nephrology",bw:["Non-anion gap acidosis","High K+","Diabetic"],ans:"Type 4 RTA",d:["Type 1 RTA","Type 2 RTA"],tp:"Type 4: hypoaldosteronism. HyperK. Common in diabetics.",ww:{"Type 1 RTA":"HypoK, distal.","Type 2 RTA":"HypoK, proximal."}},
  {id:"ne013",subj:"Nephrology",bw:["Flank pain","Hematuria","Calcium oxalate crystals"],ans:"Calcium Oxalate Kidney Stone",d:["Uric Acid Stone","Struvite Stone"],tp:"Most common stone. Envelope-shaped crystals. CT without contrast for diagnosis.",ww:{"Uric Acid Stone":"Radiolucent, gout association.","Struvite Stone":"Staghorn, UTI with urease organism."}},
  {id:"ne014",subj:"Nephrology",bw:["Staghorn calculus","Recurrent UTI","Proteus"],ans:"Struvite Stone",d:["Calcium Stone","Cystine Stone"],tp:"Struvite: MgNH4PO4. Urease-positive organisms. Coffin-lid crystals.",ww:{"Calcium Stone":"Envelope crystals.","Cystine Stone":"Hexagonal crystals."}},
  {id:"ne015",subj:"Nephrology",bw:["SIADH","Euvolemic hyponatremia","Concentrated urine"],ans:"SIADH",d:["Psychogenic Polydipsia","Adrenal Insufficiency"],tp:"SIADH: euvolemic hypoNa, urine osm >100, urine Na >40. Fluid restrict.",ww:{"Psychogenic Polydipsia":"Dilute urine, osm <100.","Adrenal Insufficiency":"Hypovolemic, hyperK."}},
  {id:"ne016",subj:"Nephrology",bw:["Chvostek sign","Trousseau sign","Prolonged QT"],ans:"Hypocalcemia",d:["Hyperkalemia","Hypomagnesemia"],tp:"Hypocalcemia: neuromuscular irritability. Common post-thyroidectomy.",ww:{"Hyperkalemia":"Peaked T, widened QRS.","Hypomagnesemia":"Must correct Mg to correct Ca."}},

  // ╔══════════════════════════════════════════════════╗
  // ║             PSYCHIATRY (93-120)                  ║
  // ╚══════════════════════════════════════════════════╝

  {id:"p001",subj:"Psychiatry",bw:["Grandiosity","Decreased sleep","Pressured speech"],ans:"Bipolar I — Manic Episode",d:["ADHD","Schizophrenia"],tp:"Mania: DIG FAST. ≥1 week or hospitalization. Lithium or valproate.",ww:{"ADHD":"Chronic from childhood, no grandiosity.","Schizophrenia":">6 months, flat affect."}},
  {id:"p002",subj:"Psychiatry",bw:["Combat veteran","Flashbacks","Hypervigilance"],ans:"PTSD",d:["Acute Stress Disorder","GAD"],tp:"PTSD: >1 month post-trauma. Intrusion, avoidance, hyperarousal.",ww:{"Acute Stress Disorder":"<1 month.","GAD":"No specific trauma."}},
  {id:"p003",subj:"Psychiatry",bw:["NMS","Lead-pipe rigidity","Hyperthermia","Antipsychotic"],ans:"Neuroleptic Malignant Syndrome",d:["Serotonin Syndrome","Malignant Hyperthermia"],tp:"NMS: dantrolene + bromocriptine. Stop antipsychotic. No clonus.",ww:{"Serotonin Syndrome":"Clonus, hyperreflexia, serotonergic drugs.","Malignant Hyperthermia":"Inhaled anesthetics/succinylcholine."}},
  {id:"p004",subj:"Psychiatry",bw:["Serotonin syndrome","Clonus","Hyperthermia","Drug interaction"],ans:"Serotonin Syndrome",d:["NMS","Malignant Hyperthermia"],tp:"SS: clonus + agitation + hyperthermia. Cyproheptadine. Stop serotonergic drugs.",ww:{"NMS":"Lead-pipe rigidity, no clonus.","Malignant Hyperthermia":"Anesthetic trigger."}},
  {id:"p005",subj:"Psychiatry",bw:["Persistent sadness","Anhedonia","≥2 weeks"],ans:"Major Depressive Disorder",d:["Adjustment Disorder","Persistent Depressive Disorder"],tp:"MDD: ≥5 SIG E CAPS criteria for ≥2 weeks. SSRIs first-line.",ww:{"Adjustment Disorder":"Identifiable stressor, <6 months.","Persistent Depressive Disorder":"Milder, ≥2 years."}},
  {id:"p006",subj:"Psychiatry",bw:["Auditory hallucinations","Flat affect","6+ months"],ans:"Schizophrenia",d:["Brief Psychotic Disorder","Schizoaffective"],tp:"Schizophrenia: ≥6 months with ≥1 month active phase. Positive + negative symptoms.",ww:{"Brief Psychotic Disorder":"<1 month, full recovery.","Schizoaffective":"Concurrent mood disorder criteria."}},
  {id:"p007",subj:"Psychiatry",bw:["Fear of social situations","Performance anxiety"],ans:"Social Anxiety Disorder",d:["Avoidant Personality Disorder","Agoraphobia"],tp:"Social anxiety: marked fear of scrutiny. CBT + SSRIs. Beta-blockers for performance.",ww:{"Avoidant Personality Disorder":"Pervasive pattern across situations.","Agoraphobia":"Fear of being trapped."}},
  {id:"p008",subj:"Psychiatry",bw:["Recurrent panic attacks","Fear of next attack"],ans:"Panic Disorder",d:["GAD","Pheochromocytoma"],tp:"Panic: unexpected attacks + persistent worry. SSRIs first-line.",ww:{"GAD":"Chronic worry, not episodic.","Pheochromocytoma":"Episodic HTN, diaphoresis."}},
  {id:"p009",subj:"Psychiatry",bw:["Obsessive thoughts","Compulsive rituals","Ego-dystonic"],ans:"OCD",d:["OCPD","GAD"],tp:"OCD: ego-dystonic. SSRIs + CBT with exposure/response prevention.",ww:{"OCPD":"Ego-syntonic perfectionism.","GAD":"Worry without rituals."}},
  {id:"p010",subj:"Psychiatry",bw:["Anorexia","BMI <18.5","Fear of weight gain"],ans:"Anorexia Nervosa",d:["Bulimia Nervosa","ARFID"],tp:"AN: highest mortality of any psychiatric diagnosis. Restrictive eating, distorted body image.",ww:{"Bulimia Nervosa":"Binge-purge, usually normal weight.","ARFID":"No body image distortion."}},
  {id:"p011",subj:"Psychiatry",bw:["Binge eating","Purging","Parotid enlargement"],ans:"Bulimia Nervosa",d:["Anorexia Nervosa","Binge Eating Disorder"],tp:"Bulimia: binge-purge. Metabolic alkalosis, dental erosion, Russell sign.",ww:{"Anorexia Nervosa":"Restriction, low BMI.","Binge Eating Disorder":"No purging."}},
  {id:"p012",subj:"Psychiatry",bw:["Conversion","Neurologic symptom","No organic cause"],ans:"Conversion Disorder",d:["Malingering","Somatic Symptom Disorder"],tp:"Conversion (functional neurological): involuntary, inconsistent with pathology.",ww:{"Malingering":"Intentional, external incentive.","Somatic Symptom Disorder":"Excessive thoughts about symptoms."}},
  {id:"p013",subj:"Psychiatry",bw:["Intentional symptoms","Sick role","No external gain"],ans:"Factitious Disorder",d:["Malingering","Somatic Symptom Disorder"],tp:"Factitious (Munchausen): conscious fabrication for internal gain.",ww:{"Malingering":"External gain (money, disability).","Somatic Symptom Disorder":"Not fabricated."}},
  {id:"p014",subj:"Psychiatry",bw:["Alcohol withdrawal","Tremor","Seizures","Visual hallucinations"],ans:"Delirium Tremens",d:["Hepatic Encephalopathy","Wernicke"],tp:"DT: 2-5 days after last drink. Autonomic instability. Benzodiazepines.",ww:{"Hepatic Encephalopathy":"Asterixis, elevated ammonia.","Wernicke":"Ophthalmoplegia, ataxia."}},
  {id:"p015",subj:"Psychiatry",bw:["Tardive dyskinesia","Lip smacking","Chronic antipsychotic"],ans:"Tardive Dyskinesia",d:["Akathisia","Acute Dystonia"],tp:"TD: chronic D2 blockade. Switch to clozapine or valbenazine.",ww:{"Akathisia":"Restlessness, inability to sit still.","Acute Dystonia":"Acute muscle spasm, benztropine."}},
  {id:"p016",subj:"Psychiatry",bw:["Lithium tremor","Hypothyroidism","Nephrogenic DI"],ans:"Lithium Side Effects",d:["Valproate Side Effects","Carbamazepine Side Effects"],tp:"Lithium: narrow therapeutic index. Monitor levels, thyroid, renal. Teratogen (Ebstein).",ww:{"Valproate Side Effects":"Hepatotoxicity, pancreatitis, neural tube defects.","Carbamazepine Side Effects":"Aplastic anemia, SIADH, SJS."}},

  // ╔══════════════════════════════════════════════════╗
  // ║           GASTROENTEROLOGY (121-145)             ║
  // ╚══════════════════════════════════════════════════╝

  {id:"g001",subj:"Gastroenterology",bw:["Signet ring cells"],ans:"Diffuse Gastric Cancer",d:["Intestinal Gastric Cancer","MALT Lymphoma"],tp:"Signet ring = diffuse/linitis plastica. Poor prognosis. CDH1 mutation.",ww:{"Intestinal Gastric Cancer":"Glandular, H. pylori.","MALT Lymphoma":"H. pylori eradication responsive."}},
  {id:"g002",subj:"Gastroenterology",bw:["Epigastric pain radiating to back","Elevated lipase"],ans:"Acute Pancreatitis",d:["Peptic Ulcer","Cholecystitis"],tp:"Lipase more specific. #1 gallstones, #2 alcohol.",ww:{"Peptic Ulcer":"Meal-related, H. pylori/NSAIDs.","Cholecystitis":"RUQ post-fatty meal, Murphy sign."}},
  {id:"g003",subj:"Gastroenterology",bw:["Bloody diarrhea","Continuous inflammation","Starts at rectum"],ans:"Ulcerative Colitis",d:["Crohn Disease","Infectious Colitis"],tp:"UC: continuous mucosal, starts rectum. Risk: toxic megacolon, colon cancer.",ww:{"Crohn Disease":"Skip lesions, transmural, fistulas.","Infectious Colitis":"Acute, positive cultures."}},
  {id:"g004",subj:"Gastroenterology",bw:["Skip lesions","Transmural","Cobblestone","Fistulas"],ans:"Crohn Disease",d:["Ulcerative Colitis","Ischemic Colitis"],tp:"Crohn: mouth to anus, non-caseating granulomas, strictures.",ww:{"Ulcerative Colitis":"Continuous, mucosal only.","Ischemic Colitis":"Elderly, watershed areas."}},
  {id:"g005",subj:"Gastroenterology",bw:["Dysphagia solids AND liquids","Bird-beak sign"],ans:"Achalasia",d:["Esophageal Carcinoma","Diffuse Esophageal Spasm"],tp:"Achalasia: failure of LES relaxation, absent peristalsis. Manometry diagnostic.",ww:{"Esophageal Carcinoma":"Progressive solids only.","Diffuse Esophageal Spasm":"Corkscrew, intermittent."}},
  {id:"g006",subj:"Gastroenterology",bw:["Progressive solid dysphagia","Weight loss"],ans:"Esophageal Carcinoma",d:["Esophageal Stricture","Achalasia"],tp:"Progressive solids + weight loss = malignancy until proven otherwise.",ww:{"Esophageal Stricture":"History of GERD, gradual.","Achalasia":"Both solids AND liquids."}},
  {id:"g007",subj:"Gastroenterology",bw:["RUQ pain","Post-fatty meal","Murphy sign"],ans:"Acute Cholecystitis",d:["Choledocholithiasis","Ascending Cholangitis"],tp:"Cholecystitis: cystic duct obstruction. US: wall thickening, pericholecystic fluid.",ww:{"Choledocholithiasis":"Dilated CBD, elevated bilirubin.","Ascending Cholangitis":"Charcot triad: fever, RUQ, jaundice."}},
  {id:"g008",subj:"Gastroenterology",bw:["Fever","RUQ pain","Jaundice"],ans:"Ascending Cholangitis",d:["Cholecystitis","Hepatitis"],tp:"Charcot triad. Reynolds pentad adds hypotension + AMS. ERCP urgently.",ww:{"Cholecystitis":"No jaundice typically.","Hepatitis":"No RUQ tenderness typically."}},
  {id:"g009",subj:"Gastroenterology",bw:["Painless jaundice","Weight loss","Courvoisier sign"],ans:"Pancreatic Head Cancer",d:["Cholangiocarcinoma","Gallstone Obstruction"],tp:"Pancreatic head: painless obstructive jaundice, palpable gallbladder.",ww:{"Cholangiocarcinoma":"Bile duct cancer, rarer.","Gallstone Obstruction":"Usually painful."}},
  {id:"g010",subj:"Gastroenterology",bw:["Barrett esophagus","Intestinal metaplasia"],ans:"Barrett Esophagus",d:["Esophageal Adenocarcinoma","Eosinophilic Esophagitis"],tp:"Barrett: squamous → intestinal metaplasia from chronic GERD. Cancer risk.",ww:{"Esophageal Adenocarcinoma":"Malignant transformation of Barrett.","Eosinophilic Esophagitis":"Young, atopic, rings."}},
  {id:"g011",subj:"Gastroenterology",bw:["Hematemesis after forceful vomiting"],ans:"Mallory-Weiss Tear",d:["Boerhaave Syndrome","Esophageal Varices"],tp:"Mallory-Weiss: partial mucosal tear at GEJ. Usually self-limited.",ww:{"Boerhaave Syndrome":"Full-thickness perforation, pneumomediastinum.","Esophageal Varices":"Cirrhosis, large-volume bleed."}},
  {id:"g012",subj:"Gastroenterology",bw:["Currant jelly stool","Child","Sausage-shaped mass"],ans:"Intussusception",d:["Volvulus","Meckel Diverticulum"],tp:"Intussusception: telescoping bowel, target sign US. Air/contrast enema reduces.",ww:{"Volvulus":"Sigmoid/cecal twisting.","Meckel Diverticulum":"Painless lower GI bleed."}},
  {id:"g013",subj:"Gastroenterology",bw:["Anti-smooth muscle antibodies","Young woman","Hepatitis"],ans:"Autoimmune Hepatitis",d:["Viral Hepatitis","Primary Biliary Cholangitis"],tp:"AIH: ANA, anti-smooth muscle. Steroids + azathioprine.",ww:{"Viral Hepatitis":"Viral serologies positive.","Primary Biliary Cholangitis":"Anti-mitochondrial Ab."}},
  {id:"g014",subj:"Gastroenterology",bw:["Anti-mitochondrial antibody","Pruritus","Cholestatic"],ans:"Primary Biliary Cholangitis",d:["Primary Sclerosing Cholangitis","Autoimmune Hepatitis"],tp:"PBC: granulomatous bile duct destruction. Middle-aged women.",ww:{"Primary Sclerosing Cholangitis":"Beading on MRCP, UC association.","Autoimmune Hepatitis":"Anti-smooth muscle."}},
  {id:"g015",subj:"Gastroenterology",bw:["Beading of bile ducts","UC association"],ans:"Primary Sclerosing Cholangitis",d:["Primary Biliary Cholangitis","Cholangiocarcinoma"],tp:"PSC: onion-skin fibrosis. p-ANCA. Risk of cholangiocarcinoma.",ww:{"Primary Biliary Cholangitis":"Anti-mitochondrial, no UC.","Cholangiocarcinoma":"Malignant complication."}},
  {id:"g016",subj:"Gastroenterology",bw:["Celiac disease","Anti-tTG","Villous atrophy"],ans:"Celiac Disease",d:["Tropical Sprue","Whipple Disease"],tp:"Celiac: gluten sensitivity, HLA-DQ2/DQ8. Anti-tTG IgA most sensitive.",ww:{"Tropical Sprue":"Travel to tropics, responds to antibiotics.","Whipple Disease":"PAS-positive macrophages."}},

  // ╔══════════════════════════════════════════════════╗
  // ║            PULMONOLOGY (146-165)                 ║
  // ╚══════════════════════════════════════════════════╝

  {id:"pu001",subj:"Pulmonology",bw:["Sudden dyspnea","Pleuritic pain","Recent surgery"],ans:"Pulmonary Embolism",d:["Pneumothorax","Pneumonia"],tp:"PE: CT angiography diagnostic. Wells criteria for risk stratification.",ww:{"Pneumothorax":"Absent breath sounds, hyperresonance.","Pneumonia":"Fever, productive cough."}},
  {id:"pu002",subj:"Pulmonology",bw:["Young patient","Basilar emphysema","Liver disease"],ans:"Alpha-1 Antitrypsin Deficiency",d:["COPD","Cystic Fibrosis"],tp:"A1AT: panacinar emphysema lower lobes + liver cirrhosis. PAS-positive globules.",ww:{"COPD":"Upper lobe centrilobular, smoking.","Cystic Fibrosis":"Bronchiectasis, Pseudomonas."}},
  {id:"pu003",subj:"Pulmonology",bw:["Tall thin male","Sudden dyspnea","Absent breath sounds"],ans:"Spontaneous Pneumothorax",d:["PE","Tension Pneumothorax"],tp:"Primary spontaneous: tall thin young males, apical bleb rupture.",ww:{"PE":"Normal breath sounds.","Tension Pneumothorax":"Hemodynamic instability, tracheal deviation."}},
  {id:"pu004",subj:"Pulmonology",bw:["Tracheal deviation","Hypotension","Absent breath sounds"],ans:"Tension Pneumothorax",d:["Cardiac Tamponade","Massive PE"],tp:"Tension pneumo: clinical diagnosis. Needle decompression 2nd ICS MCL.",ww:{"Cardiac Tamponade":"Muffled sounds, no tracheal deviation.","Massive PE":"No tracheal deviation."}},
  {id:"pu005",subj:"Pulmonology",bw:["Non-caseating granulomas","Bilateral hilar LAD","Young Black woman"],ans:"Sarcoidosis",d:["Tuberculosis","Lymphoma"],tp:"Sarcoidosis: elevated ACE, hypercalcemia. Steroids if symptomatic.",ww:{"Tuberculosis":"Caseating granulomas, upper lobe.","Lymphoma":"B symptoms, biopsy diagnostic."}},
  {id:"pu006",subj:"Pulmonology",bw:["Clubbing","Honeycombing","Lower lobe fibrosis","UIP"],ans:"Idiopathic Pulmonary Fibrosis",d:["Sarcoidosis","Asbestosis"],tp:"IPF: UIP pattern, lower lobe. Pirfenidone/nintedanib.",ww:{"Sarcoidosis":"Upper/mid zone, granulomas.","Asbestosis":"Asbestos exposure, pleural plaques."}},
  {id:"pu007",subj:"Pulmonology",bw:["Occupational exposure","Asbestos","Pleural plaques"],ans:"Asbestosis",d:["Mesothelioma","IPF"],tp:"Asbestosis: lower lobe fibrosis + pleural plaques. Increased cancer risk.",ww:{"Mesothelioma":"Malignant pleural tumor, calretinin+.","IPF":"No exposure history."}},
  {id:"pu008",subj:"Pulmonology",bw:["Barrel chest","Hyperinflation","Smoking"],ans:"COPD/Emphysema",d:["Asthma","Bronchiectasis"],tp:"COPD: FEV1/FVC <0.7, irreversible. Smoking cessation most important.",ww:{"Asthma":"Reversible, younger.","Bronchiectasis":"Chronic productive cough, dilated airways."}},
  {id:"pu009",subj:"Pulmonology",bw:["Reversible airflow obstruction","Eosinophils","Wheezing"],ans:"Asthma",d:["COPD","ABPA"],tp:"Asthma: reversible with bronchodilator. Inhaled corticosteroids mainstay.",ww:{"COPD":"Irreversible, older.","ABPA":"Aspergillus, central bronchiectasis."}},
  {id:"pu010",subj:"Pulmonology",bw:["Pancoast tumor","Horner syndrome","Shoulder pain"],ans:"Pancoast Tumor",d:["Cervical Radiculopathy","Lymphoma"],tp:"Pancoast: superior sulcus, ipsilateral Horner (ptosis, miosis, anhidrosis).",ww:{"Cervical Radiculopathy":"No Horner.","Lymphoma":"Mediastinal mass, B symptoms."}},

  // ╔══════════════════════════════════════════════════╗
  // ║         INFECTIOUS DISEASE (166-190)             ║
  // ╚══════════════════════════════════════════════════╝

  {id:"id001",subj:"Infectious Disease",bw:["Erythema migrans","Tick bite","Northeast US"],ans:"Lyme Disease",d:["RMSF","Ehrlichiosis"],tp:"Borrelia burgdorferi: target lesion. Early: doxycycline. Late: arthritis, Bell palsy, AV block.",ww:{"RMSF":"Petechial rash wrists/ankles → central.","Ehrlichiosis":"Morulae in monocytes."}},
  {id:"id002",subj:"Infectious Disease",bw:["HIV+","CD4 <200","Ground-glass opacities"],ans:"PCP Pneumonia",d:["TB","CMV Pneumonitis"],tp:"PCP: bilateral GGOs, dry cough. TMP-SMX treatment and prophylaxis.",ww:{"TB":"Upper lobe cavitary.","CMV Pneumonitis":"CD4 <50, owl-eye inclusions."}},
  {id:"id003",subj:"Infectious Disease",bw:["Ring-enhancing brain lesion","CD4 <100"],ans:"Toxoplasmosis",d:["Primary CNS Lymphoma","Brain Abscess"],tp:"Toxo in AIDS: multiple ring-enhancing. Pyrimethamine + sulfadiazine.",ww:{"Primary CNS Lymphoma":"Solitary periventricular, EBV.","Brain Abscess":"Usually solitary."}},
  {id:"id004",subj:"Infectious Disease",bw:["Fever","Petechial rash","Starts at wrists/ankles"],ans:"Rocky Mountain Spotted Fever",d:["Meningococcemia","Lyme Disease"],tp:"RMSF: Rickettsia, Dermacentor tick. Centripetal spread. Doxycycline.",ww:{"Meningococcemia":"Purpura fulminans, DIC.","Lyme Disease":"Erythema migrans, not petechial."}},
  {id:"id005",subj:"Infectious Disease",bw:["Rice-water stool","Profuse watery diarrhea"],ans:"Cholera",d:["Shigella","ETEC"],tp:"Vibrio cholerae: AB toxin activates Gs → cAMP. Massive secretory diarrhea.",ww:{"Shigella":"Bloody/mucoid, invasion.","ETEC":"LT (cAMP) and ST (cGMP) toxins."}},
  {id:"id006",subj:"Infectious Disease",bw:["Bloody diarrhea","HUS","O157:H7"],ans:"EHEC",d:["Shigella","Salmonella"],tp:"EHEC: Shiga-like toxin. Do NOT give antibiotics (increases toxin release).",ww:{"Shigella":"Can treat with antibiotics.","Salmonella":"Inflammatory, reptile exposure."}},
  {id:"id007",subj:"Infectious Disease",bw:["Owl-eye inclusions","CD4 <50","Retinitis"],ans:"CMV Infection",d:["HSV","Toxoplasmosis"],tp:"CMV: most common opportunistic in AIDS. Retinitis, colitis, esophagitis.",ww:{"HSV":"Punched-out ulcers.","Toxoplasmosis":"Brain lesions."}},
  {id:"id008",subj:"Infectious Disease",bw:["White cottage-cheese plaques","CD4 <200"],ans:"Oral Candidiasis",d:["Oral Hairy Leukoplakia","Aphthous Ulcer"],tp:"Thrush: Candida. Scraped off (unlike OHL). Fluconazole.",ww:{"Oral Hairy Leukoplakia":"EBV, lateral tongue, cannot scrape.","Aphthous Ulcer":"Painful, no plaques."}},
  {id:"id009",subj:"Infectious Disease",bw:["India ink positive","CD4 <100","Meningitis"],ans:"Cryptococcal Meningitis",d:["Bacterial Meningitis","TB Meningitis"],tp:"Crypto: encapsulated yeast. India ink, CrAg. Elevated opening pressure.",ww:{"Bacterial Meningitis":"Gram stain/culture positive.","TB Meningitis":"AFB, basilar meningitis."}},
  {id:"id010",subj:"Infectious Disease",bw:["Upper lobe cavitary","Night sweats","AFB positive"],ans:"Tuberculosis",d:["Lung Abscess","Sarcoidosis"],tp:"TB: M. tuberculosis. PPD/IGRA screening. RIPE therapy.",ww:{"Lung Abscess":"Aspiration, polymicrobial.","Sarcoidosis":"Non-caseating granulomas."}},
  {id:"id011",subj:"Infectious Disease",bw:["Painless chancre","Primary syphilis"],ans:"Primary Syphilis",d:["Chancroid","Genital HSV"],tp:"Primary syphilis: painless chancre. Treponema pallidum. Darkfield microscopy.",ww:{"Chancroid":"Painful ulcer, H. ducreyi.","Genital HSV":"Painful vesicular ulcers."}},
  {id:"id012",subj:"Infectious Disease",bw:["Condylomata lata","Diffuse rash","Palms and soles"],ans:"Secondary Syphilis",d:["Drug Rash","Primary Syphilis"],tp:"Secondary: diffuse rash including palms/soles, condylomata lata.",ww:{"Drug Rash":"Medication exposure.","Primary Syphilis":"Chancre only, no rash."}},

  // ╔══════════════════════════════════════════════════╗
  // ║           ENDOCRINOLOGY (191-212)                ║
  // ╚══════════════════════════════════════════════════╝

  {id:"en001",subj:"Endocrinology",bw:["Heat intolerance","Weight loss","Exophthalmos"],ans:"Graves Disease",d:["Toxic MNG","Thyroid Storm"],tp:"Graves: anti-TSH receptor stimulating Ab. Diffuse RAI uptake.",ww:{"Toxic MNG":"Patchy uptake, older.","Thyroid Storm":"Severe + fever + AMS."}},
  {id:"en002",subj:"Endocrinology",bw:["Central obesity","Purple striae","Moon facies"],ans:"Cushing Syndrome",d:["Metabolic Syndrome","Hypothyroidism"],tp:"Excess cortisol. Screen: 24h urine, late-night salivary, dex suppression.",ww:{"Metabolic Syndrome":"No purple striae.","Hypothyroidism":"Cold intolerance, no striae."}},
  {id:"en003",subj:"Endocrinology",bw:["Cold intolerance","Weight gain","Elevated TSH"],ans:"Hypothyroidism",d:["Depression","Iron Deficiency Anemia"],tp:"Hypothyroidism: elevated TSH, low free T4. Hashimoto most common.",ww:{"Depression":"Normal TSH.","Iron Deficiency Anemia":"Fatigue but no cold intolerance."}},
  {id:"en004",subj:"Endocrinology",bw:["Pheochromocytoma","Episodic HTN","Headache","Diaphoresis"],ans:"Pheochromocytoma",d:["Essential Hypertension","Panic Disorder"],tp:"Pheo: catecholamine-secreting. 24h urine metanephrines. Alpha-block before beta.",ww:{"Essential Hypertension":"Sustained, no episodic symptoms.","Panic Disorder":"No HTN crisis."}},
  {id:"en005",subj:"Endocrinology",bw:["Hypercalcemia","Kidney stones","Elevated PTH"],ans:"Primary Hyperparathyroidism",d:["Malignancy Hypercalcemia","Sarcoidosis"],tp:"PHPT: stones, bones, groans, psychiatric overtones.",ww:{"Malignancy Hypercalcemia":"PTHrP elevated, PTH suppressed.","Sarcoidosis":"1-alpha hydroxylase → calcitriol."}},
  {id:"en006",subj:"Endocrinology",bw:["MEN 1","Pituitary","Parathyroid","Pancreas"],ans:"MEN Type 1",d:["MEN 2A","MEN 2B"],tp:"MEN1: 3 Ps. Menin gene mutation.",ww:{"MEN 2A":"Medullary thyroid, pheo, parathyroid.","MEN 2B":"Mucosal neuromas, marfanoid."}},
  {id:"en007",subj:"Endocrinology",bw:["Medullary thyroid cancer","Pheochromocytoma","RET"],ans:"MEN Type 2A",d:["MEN 1","MEN 2B"],tp:"MEN2A: medullary thyroid, pheo, hyperparathyroidism. RET mutation.",ww:{"MEN 1":"Pituitary, parathyroid, pancreas.","MEN 2B":"Mucosal neuromas, no hyperparathyroidism."}},
  {id:"en008",subj:"Endocrinology",bw:["Hypoglycemia","Elevated insulin","Elevated C-peptide"],ans:"Insulinoma",d:["Exogenous Insulin","Sulfonylurea Use"],tp:"Insulinoma: beta-cell tumor. High insulin + high C-peptide.",ww:{"Exogenous Insulin":"High insulin, LOW C-peptide.","Sulfonylurea Use":"Must check drug screen."}},
  {id:"en009",subj:"Endocrinology",bw:["Acromegaly","Coarsened features","Elevated IGF-1"],ans:"Acromegaly",d:["Gigantism","Hypothyroidism"],tp:"Acromegaly: GH-secreting adenoma in adults. Screen IGF-1.",ww:{"Gigantism":"Before growth plate closure.","Hypothyroidism":"No coarsened features."}},
  {id:"en010",subj:"Endocrinology",bw:["Galactorrhea","Amenorrhea","Elevated prolactin"],ans:"Prolactinoma",d:["Hypothyroidism","Drug-Induced Hyperprolactinemia"],tp:"Prolactinoma: most common pituitary adenoma. Dopamine agonists.",ww:{"Hypothyroidism":"TRH stimulates PRL, but TSH elevated.","Drug-Induced Hyperprolactinemia":"Antipsychotics — check meds."}},
  {id:"en011",subj:"Endocrinology",bw:["Adrenal crisis","Hypotension","HypoNa","HyperK"],ans:"Acute Adrenal Insufficiency",d:["Sepsis","SIADH"],tp:"Adrenal crisis: IV hydrocortisone emergently.",ww:{"Sepsis":"Can precipitate adrenal crisis.","SIADH":"Euvolemic hypoNa, normal K."}},
  {id:"en012",subj:"Endocrinology",bw:["Hyperpigmentation","Low cortisol","Elevated ACTH"],ans:"Primary Adrenal Insufficiency (Addison)",d:["Secondary Adrenal Insufficiency","Cushing"],tp:"Addison: autoimmune. High ACTH → hyperpigmentation.",ww:{"Secondary Adrenal Insufficiency":"Low ACTH, no hyperpigmentation.","Cushing":"Elevated cortisol."}},
  {id:"en013",subj:"Endocrinology",bw:["DKA","Fruity breath","Kussmaul","Type 1 DM"],ans:"Diabetic Ketoacidosis",d:["HHS","Metabolic Alkalosis"],tp:"DKA: T1DM, anion gap acidosis, ketones. Insulin + fluids + K+ monitoring.",ww:{"HHS":"T2DM, glucose >600, minimal ketosis.","Metabolic Alkalosis":"Vomiting, contraction."}},

  // ╔══════════════════════════════════════════════════╗
  // ║        HEMATOLOGY/ONCOLOGY (213-232)             ║
  // ╚══════════════════════════════════════════════════╝

  {id:"he001",subj:"Hematology/Oncology",bw:["Auer rods","DIC","t(15;17)"],ans:"Acute Promyelocytic Leukemia",d:["AML (other)","CML"],tp:"APL: PML-RARA. ATRA + arsenic trioxide.",ww:{"AML (other)":"No t(15;17).","CML":"t(9;22), mature granulocytes."}},
  {id:"he002",subj:"Hematology/Oncology",bw:["Reed-Sternberg cells","Bimodal age"],ans:"Hodgkin Lymphoma",d:["Non-Hodgkin Lymphoma","Infectious Mono"],tp:"RS cells CD15+/CD30+. Contiguous spread. B symptoms.",ww:{"Non-Hodgkin Lymphoma":"No RS cells.","Infectious Mono":"Reactive T cells, Monospot."}},
  {id:"he003",subj:"Hematology/Oncology",bw:["Smudge cells","Elderly","Lymphocytosis"],ans:"Chronic Lymphocytic Leukemia",d:["Small Lymphocytic Lymphoma","Mantle Cell"],tp:"CLL: most common adult leukemia in West. CD5+ B cells.",ww:{"Small Lymphocytic Lymphoma":"Same disease, tissue predominant.","Mantle Cell":"Cyclin D1, t(11;14)."}},
  {id:"he004",subj:"Hematology/Oncology",bw:["Philadelphia chromosome","t(9;22)","BCR-ABL"],ans:"Chronic Myeloid Leukemia",d:["CLL","AML"],tp:"CML: BCR-ABL tyrosine kinase. Imatinib.",ww:{"CLL":"Lymphoid, smudge cells.","AML":"Acute, blasts >20%."}},
  {id:"he005",subj:"Hematology/Oncology",bw:["Child","Lymphoblasts","CD10+"],ans:"Acute Lymphoblastic Leukemia",d:["AML","Lymphoma"],tp:"ALL: most common childhood cancer. TdT+, CD10+. High cure rate.",ww:{"AML":"Myeloid markers, Auer rods.","Lymphoma":"Solid tissue mass."}},
  {id:"he006",subj:"Hematology/Oncology",bw:["Starry-sky pattern","Jaw mass","c-myc"],ans:"Burkitt Lymphoma",d:["Hodgkin","DLBCL"],tp:"Burkitt: t(8;14) c-myc. EBV associated. Rapidly growing.",ww:{"Hodgkin":"RS cells.","DLBCL":"Most common NHL, no starry-sky."}},
  {id:"he007",subj:"Hematology/Oncology",bw:["Sickle cells","Vaso-occlusive crisis"],ans:"Sickle Cell Disease",d:["Thalassemia","G6PD Deficiency"],tp:"SCD: HbS polymerizes low O₂. Autosplenectomy. Parvovirus B19 aplastic crisis.",ww:{"Thalassemia":"Target cells, no sickling.","G6PD Deficiency":"Heinz bodies, oxidant stress."}},
  {id:"he008",subj:"Hematology/Oncology",bw:["Heinz bodies","Bite cells","Oxidant stress"],ans:"G6PD Deficiency",d:["Sickle Cell","Hereditary Spherocytosis"],tp:"G6PD: X-linked. Hemolysis after fava beans, sulfonamides, infections.",ww:{"Sickle Cell":"Sickle cells, chronic.","Hereditary Spherocytosis":"Spherocytes, osmotic fragility."}},
  {id:"he009",subj:"Hematology/Oncology",bw:["Spherocytes","Positive osmotic fragility"],ans:"Hereditary Spherocytosis",d:["AIHA","G6PD Deficiency"],tp:"HS: spectrin/ankyrin defect. Extravascular hemolysis. Splenectomy if severe.",ww:{"AIHA":"Positive direct Coombs.","G6PD Deficiency":"Heinz bodies, episodic."}},
  {id:"he010",subj:"Hematology/Oncology",bw:["Schistocytes","Thrombocytopenia","Renal failure","Child"],ans:"Hemolytic Uremic Syndrome",d:["TTP","DIC"],tp:"HUS: EHEC → MAHA + thrombocytopenia + renal failure.",ww:{"TTP":"Pentad with fever + neuro, ADAMTS13.","DIC":"Prolonged PT/PTT."}},
  {id:"he011",subj:"Hematology/Oncology",bw:["Schistocytes","Fever","Neurologic symptoms","ADAMTS13"],ans:"TTP",d:["HUS","DIC"],tp:"TTP: pentad. Plasmapheresis urgently.",ww:{"HUS":"Renal predominant, post-diarrheal.","DIC":"Consumptive coagulopathy."}},
  {id:"he012",subj:"Hematology/Oncology",bw:["Iron deficiency","Microcytic","Low ferritin"],ans:"Iron Deficiency Anemia",d:["Thalassemia","Anemia of Chronic Disease"],tp:"IDA: low ferritin most specific. Elevated TIBC.",ww:{"Thalassemia":"Normal/elevated iron, high RBC count.","Anemia of Chronic Disease":"Low TIBC, normal ferritin."}},
  {id:"he013",subj:"Hematology/Oncology",bw:["Rouleaux formation","Lytic lesions","M-spike"],ans:"Multiple Myeloma",d:["MGUS","Waldenström"],tp:"MM: CRAB — Calcium, Renal, Anemia, Bone.",ww:{"MGUS":"<10% plasma cells, no CRAB.","Waldenström":"IgM, hyperviscosity."}},

  // ╔══════════════════════════════════════════════════╗
  // ║           RHEUMATOLOGY (233-248)                 ║
  // ╚══════════════════════════════════════════════════╝

  {id:"rh001",subj:"Rheumatology",bw:["Podagra","Negatively birefringent crystals"],ans:"Gout",d:["Pseudogout","Septic Arthritis"],tp:"MSU crystals, yellow under parallel light. First MTP classic.",ww:{"Pseudogout":"CPPD, positively birefringent, knee.","Septic Arthritis":">50K WBC, culture positive."}},
  {id:"rh002",subj:"Rheumatology",bw:["Rhomboid crystals","Positively birefringent","Knee"],ans:"Pseudogout",d:["Gout","Osteoarthritis"],tp:"CPPD crystals, blue under parallel light. Knee most common.",ww:{"Gout":"MSU, negatively birefringent, first MTP.","Osteoarthritis":"No crystals, degenerative."}},
  {id:"rh003",subj:"Rheumatology",bw:["Young woman","Malar rash","ANA positive"],ans:"Systemic Lupus Erythematosus",d:["Rheumatoid Arthritis","Dermatomyositis"],tp:"SLE: anti-dsDNA specific, ANA sensitive. Multi-organ.",ww:{"Rheumatoid Arthritis":"Symmetric joint, RF/anti-CCP.","Dermatomyositis":"Heliotrope, proximal weakness."}},
  {id:"rh004",subj:"Rheumatology",bw:["Morning stiffness >1hr","Symmetric small joint","Anti-CCP"],ans:"Rheumatoid Arthritis",d:["Osteoarthritis","SLE"],tp:"RA: symmetric inflammatory. Anti-CCP most specific. MTX first-line.",ww:{"Osteoarthritis":"Stiffness <30min, DIP/weight-bearing.","SLE":"Multi-organ, malar rash."}},
  {id:"rh005",subj:"Rheumatology",bw:["DIP joint","Heberden nodes","Crepitus"],ans:"Osteoarthritis",d:["Rheumatoid Arthritis","Psoriatic Arthritis"],tp:"OA: wear-and-tear, DIP Heberden and PIP Bouchard nodes.",ww:{"Rheumatoid Arthritis":"MCP/PIP, RF+.","Psoriatic Arthritis":"DIP + nail changes + psoriasis."}},
  {id:"rh006",subj:"Rheumatology",bw:["Skin thickening","Raynaud","Anti-Scl-70"],ans:"Diffuse Scleroderma",d:["Limited Scleroderma","SLE"],tp:"Diffuse SSc: widespread skin, anti-topoisomerase. Renal crisis risk.",ww:{"Limited Scleroderma":"CREST, anti-centromere.","SLE":"Malar rash."}},
  {id:"rh007",subj:"Rheumatology",bw:["CREST syndrome","Anti-centromere antibody"],ans:"Limited Scleroderma",d:["Diffuse Scleroderma","PBC"],tp:"CREST: Calcinosis, Raynaud, Esophageal, Sclerodactyly, Telangiectasia.",ww:{"Diffuse Scleroderma":"Anti-Scl-70, widespread.","PBC":"Anti-mitochondrial."}},
  {id:"rh008",subj:"Rheumatology",bw:["Dry eyes","Dry mouth","Anti-Ro/SSA"],ans:"Sjögren Syndrome",d:["SLE","Sarcoidosis"],tp:"Sjögren: lymphocytic infiltration lacrimal/salivary. MALT lymphoma risk.",ww:{"SLE":"Multi-organ.","Sarcoidosis":"Granulomas, hilar LAD."}},
  {id:"rh009",subj:"Rheumatology",bw:["Heliotrope rash","Gottron papules","Proximal weakness"],ans:"Dermatomyositis",d:["Polymyositis","SLE"],tp:"DM: proximal weakness + skin rashes. Screen for malignancy.",ww:{"Polymyositis":"No skin findings.","SLE":"No proximal weakness."}},
  {id:"rh010",subj:"Rheumatology",bw:["Bamboo spine","HLA-B27","Young male","Morning back stiffness"],ans:"Ankylosing Spondylitis",d:["Mechanical Back Pain","Psoriatic Arthritis"],tp:"AS: sacroiliitis, bamboo spine. Improves with exercise.",ww:{"Mechanical Back Pain":"Worse with activity.","Psoriatic Arthritis":"Peripheral + skin."}},
  {id:"rh011",subj:"Rheumatology",bw:["Sausage digits","Nail pitting","Psoriatic skin"],ans:"Psoriatic Arthritis",d:["RA","Reactive Arthritis"],tp:"PsA: DIP, dactylitis, nail changes. RF negative.",ww:{"RA":"Symmetric MCP/PIP, RF+.","Reactive Arthritis":"Post-infectious."}},
  {id:"rh012",subj:"Rheumatology",bw:["Urethritis","Conjunctivitis","Arthritis","Post-infection"],ans:"Reactive Arthritis",d:["Psoriatic Arthritis","Gonococcal Arthritis"],tp:"Reactive: can't see, can't pee, can't climb a tree. HLA-B27.",ww:{"Psoriatic Arthritis":"Skin psoriasis, nail changes.","Gonococcal Arthritis":"Positive synovial culture."}},

  // ╔══════════════════════════════════════════════════╗
  // ║          OB/GYN + PEDIATRICS (249-270)           ║
  // ╚══════════════════════════════════════════════════╝

  {id:"ob001",subj:"Obstetrics/Gynecology",bw:["Postpartum","Hypertension","Seizure"],ans:"Eclampsia",d:["HELLP Syndrome","Epilepsy"],tp:"Eclampsia: seizures in preeclampsia. IV magnesium sulfate.",ww:{"HELLP Syndrome":"Hemolysis, LFTs, low platelets — no seizures.","Epilepsy":"Peripartum + HTN = eclampsia."}},
  {id:"ob002",subj:"Obstetrics/Gynecology",bw:["Preeclampsia","Proteinuria","HTN after 20 weeks"],ans:"Preeclampsia",d:["Gestational HTN","Chronic HTN"],tp:"Preeclampsia: HTN + proteinuria after 20wk. Delivery is cure.",ww:{"Gestational HTN":"No proteinuria.","Chronic HTN":"Before 20 weeks."}},
  {id:"ob003",subj:"Obstetrics/Gynecology",bw:["Painless vaginal bleeding","3rd trimester"],ans:"Placenta Previa",d:["Placental Abruption","Vasa Previa"],tp:"Previa: painless bright red. NO digital exam. US diagnostic.",ww:{"Placental Abruption":"Painful, rigid abdomen.","Vasa Previa":"Fetal distress."}},
  {id:"ob004",subj:"Obstetrics/Gynecology",bw:["Painful vaginal bleeding","Rigid abdomen"],ans:"Placental Abruption",d:["Placenta Previa","Uterine Rupture"],tp:"Abruption: painful, dark blood. Risk: HTN, cocaine, trauma.",ww:{"Placenta Previa":"Painless bright red.","Uterine Rupture":"Prior C-section, loss of station."}},
  {id:"ob005",subj:"Obstetrics/Gynecology",bw:["Grape-like vesicles","Very high β-hCG","Snowstorm US"],ans:"Hydatidiform Mole",d:["Normal Pregnancy","Choriocarcinoma"],tp:"Complete mole: 46XX paternal. Partial: triploid. Monitor β-hCG.",ww:{"Normal Pregnancy":"Normal fetus on US.","Choriocarcinoma":"Malignant, post-molar."}},
  {id:"ob006",subj:"Obstetrics/Gynecology",bw:["Ectopic pregnancy","Amenorrhea","Unilateral pain"],ans:"Ectopic Pregnancy",d:["Ovarian Torsion","Ruptured Cyst"],tp:"Ectopic: β-hCG above discriminatory zone, no IUP. Ampulla most common.",ww:{"Ovarian Torsion":"No β-hCG, absent Doppler.","Ruptured Cyst":"β-hCG negative, mid-cycle."}},
  {id:"pe001",subj:"Pediatrics",bw:["Barking cough","Steeple sign","Parainfluenza"],ans:"Croup",d:["Epiglottitis","Foreign Body"],tp:"Croup: barking seal cough, steeple sign. Dexamethasone ± nebulized epi.",ww:{"Epiglottitis":"Drooling, tripod, thumbprint sign.","Foreign Body":"Sudden, unilateral wheeze."}},
  {id:"pe002",subj:"Pediatrics",bw:["High fever 5 days","Strawberry tongue","Rash"],ans:"Kawasaki Disease",d:["Scarlet Fever","Measles"],tp:"Kawasaki: ≥5 days fever + 4/5 criteria. Coronary aneurysm risk. IVIG + aspirin.",ww:{"Scarlet Fever":"Sandpaper rash, strep.","Measles":"Koplik spots, 3 Cs."}},
  {id:"pe003",subj:"Pediatrics",bw:["Olive-shaped mass","Projectile vomiting","3-week-old"],ans:"Pyloric Stenosis",d:["Malrotation","GERD"],tp:"Pyloric stenosis: metabolic alkalosis. US diagnostic. Pyloromyotomy.",ww:{"Malrotation":"Bilious vomiting.","GERD":"Effortless spit-up."}},
  {id:"pe004",subj:"Pediatrics",bw:["Slapped cheek rash","Lacy reticular rash"],ans:"Fifth Disease",d:["Measles","Rubella"],tp:"Parvovirus B19: slapped cheeks → lacy rash. Risk: aplastic crisis in SCD.",ww:{"Measles":"Koplik spots, 3 Cs.","Rubella":"Generalized, lymphadenopathy."}},
  {id:"pe005",subj:"Pediatrics",bw:["Bilious vomiting","Newborn","Double-bubble sign"],ans:"Duodenal Atresia",d:["Pyloric Stenosis","Malrotation"],tp:"Duodenal atresia: Down syndrome association. Bilious vomiting.",ww:{"Pyloric Stenosis":"Non-bilious, 3-6 weeks.","Malrotation":"Midgut volvulus risk."}},
  {id:"pe006",subj:"Pediatrics",bw:["Non-blanching petechiae","Fever","Meningismus"],ans:"Meningococcemia",d:["ITP","Henoch-Schönlein Purpura"],tp:"N. meningitidis: purpura fulminans, Waterhouse-Friderichsen.",ww:{"ITP":"No fever, well-appearing.","Henoch-Schönlein Purpura":"Palpable purpura buttocks, no fever."}},
  {id:"pe007",subj:"Pediatrics",bw:["Ash-leaf spots","Cardiac rhabdomyoma","Seizures"],ans:"Tuberous Sclerosis Complex",d:["NF1","Sturge-Weber"],tp:"TSC: TSC1/TSC2 mutations, cortical tubers, renal angiomyolipomas, subependymal nodules. mTOR pathway involvement.",ww:{"NF1":"Café-au-lait spots, neurofibromas.","Sturge-Weber":"Port-wine stain, leptomeningeal angioma."}},

  // ╔══════════════════════════════════════════════════╗
  // ║     SURGERY + EMERGENCY MED (271-295)            ║
  // ╚══════════════════════════════════════════════════╝

  {id:"su001",subj:"Surgery",bw:["RLQ pain","McBurney point","Rebound"],ans:"Appendicitis",d:["Mesenteric Lymphadenitis","Meckel Diverticulum"],tp:"Periumbilical → RLQ migration. CT diagnostic.",ww:{"Mesenteric Lymphadenitis":"Post-URI, self-limited.","Meckel Diverticulum":"Painless GI bleed."}},
  {id:"su002",subj:"Surgery",bw:["Pulsatile abdominal mass","Back pain","Hypotension"],ans:"Ruptured AAA",d:["Renal Colic","Acute Pancreatitis"],tp:"AAA rupture triad. Screen US men 65-75 who smoked.",ww:{"Renal Colic":"Colicky, hematuria, no mass.","Acute Pancreatitis":"Elevated lipase, no mass."}},
  {id:"su003",subj:"Surgery",bw:["Air under diaphragm","Acute abdomen"],ans:"Perforated Viscus",d:["Bowel Obstruction","Pancreatitis"],tp:"Free air on upright CXR/CT = perforation. Surgical emergency.",ww:{"Bowel Obstruction":"Dilated loops, air-fluid levels.","Pancreatitis":"No free air."}},
  {id:"su004",subj:"Surgery",bw:["Post-op fever Day 1","Atelectasis"],ans:"Atelectasis",d:["Pneumonia","PE"],tp:"Wind (Day 1-2): most common early post-op fever. Incentive spirometry.",ww:{"Pneumonia":"Day 3-5.","PE":"Day 5-7."}},
  {id:"su005",subj:"Surgery",bw:["Post-op Day 5","Wound erythema","Purulent drainage"],ans:"Surgical Site Infection",d:["Seroma","Hematoma"],tp:"Wound (Day 5-7): SSI. Open, drain, antibiotics.",ww:{"Seroma":"Clear fluid, no infection.","Hematoma":"Blood collection, ecchymosis."}},
  {id:"su006",subj:"Surgery",bw:["Bowel obstruction","Dilated loops","Air-fluid levels"],ans:"Small Bowel Obstruction",d:["Large Bowel Obstruction","Ileus"],tp:"SBO: #1 adhesions from prior surgery. NGT decompression.",ww:{"Large Bowel Obstruction":"Cancer or volvulus.","Ileus":"No mechanical obstruction."}},
  {id:"su007",subj:"Surgery",bw:["Sigmoid volvulus","Coffee-bean sign","Elderly"],ans:"Sigmoid Volvulus",d:["Cecal Volvulus","SBO"],tp:"Sigmoid volvulus: coffee-bean on XR. Flexible sigmoidoscopy to decompress.",ww:{"Cecal Volvulus":"RLQ, younger, requires surgery.","SBO":"Adhesions, diffuse distension."}},
  {id:"su008",subj:"Surgery",bw:["Cullen sign","Grey Turner sign","Pancreatitis"],ans:"Hemorrhagic Pancreatitis",d:["Ruptured AAA","Retroperitoneal Hemorrhage"],tp:"Cullen (periumbilical) and Grey Turner (flank) = retroperitoneal hemorrhage.",ww:{"Ruptured AAA":"Pulsatile mass.","Retroperitoneal Hemorrhage":"Various causes."}},
  {id:"em001",subj:"Emergency Medicine",bw:["Pinpoint pupils","Respiratory depression","Needle marks"],ans:"Opioid Overdose",d:["Benzo Overdose","Organophosphate Poisoning"],tp:"Opioid triad: miosis, resp depression, AMS. Naloxone.",ww:{"Benzo Overdose":"Normal pupils.","Organophosphate Poisoning":"DUMBBELSS."}},
  {id:"em002",subj:"Emergency Medicine",bw:["Cherry-red skin","Headache","Space heater"],ans:"Carbon Monoxide Poisoning",d:["Cyanide Poisoning","Methemoglobinemia"],tp:"CO: binds Hb 200x affinity. SpO₂ falsely normal. 100% O₂.",ww:{"Cyanide Poisoning":"Almond odor, lactic acidosis.","Methemoglobinemia":"Chocolate-brown blood."}},
  {id:"em003",subj:"Emergency Medicine",bw:["Chocolate-brown blood","Cyanosis unresponsive to O₂"],ans:"Methemoglobinemia",d:["CO Poisoning","Cyanide"],tp:"MetHb: Fe²⁺→Fe³⁺. Methylene blue (contraindicated in G6PD).",ww:{"CO Poisoning":"Cherry-red.","Cyanide":"Almond odor."}},
  {id:"em004",subj:"Emergency Medicine",bw:["Hot dry red","Dilated pupils","Mad as a hatter"],ans:"Anticholinergic Toxicity",d:["Sympathomimetic","Serotonin Syndrome"],tp:"Anticholinergic: hot, dry, red, blind, mad. Physostigmine for severe.",ww:{"Sympathomimetic":"Diaphoresis present (wet).","Serotonin Syndrome":"Clonus, hyperreflexia."}},
  {id:"em005",subj:"Emergency Medicine",bw:["Osmolar gap","Vision loss"],ans:"Methanol Poisoning",d:["Ethylene Glycol","Ethanol"],tp:"Methanol: formic acid → retinal toxicity. Fomepizole.",ww:{"Ethylene Glycol":"Ca oxalate crystals, renal failure.","Ethanol":"No osmolar gap after metabolism."}},
  {id:"em006",subj:"Emergency Medicine",bw:["Ca oxalate crystals","Renal failure","Osmolar gap"],ans:"Ethylene Glycol Poisoning",d:["Methanol","Rhabdomyolysis"],tp:"Ethylene glycol: antifreeze. Fomepizole.",ww:{"Methanol":"Vision loss.","Rhabdomyolysis":"Elevated CK."}},
  {id:"em007",subj:"Emergency Medicine",bw:["Compartment syndrome","Pain out of proportion"],ans:"Compartment Syndrome",d:["DVT","Cellulitis"],tp:"Compartment syndrome: fasciotomy. Passive stretch most sensitive sign.",ww:{"DVT":"Swelling, no passive stretch pain.","Cellulitis":"Skin erythema."}},
  {id:"em008",subj:"Emergency Medicine",bw:["Salicylate toxicity","Tinnitus","Mixed acid-base"],ans:"Salicylate Poisoning",d:["Metabolic Alkalosis","Respiratory Alkalosis"],tp:"Salicylate: resp alkalosis (early) + AG metabolic acidosis (late). Alkalinize urine.",ww:{"Metabolic Alkalosis":"Vomiting.","Respiratory Alkalosis":"Simple hyperventilation."}},

  // ╔══════════════════════════════════════════════════╗
  // ║          MULTISYSTEM / MIXED (296-320)           ║
  // ╚══════════════════════════════════════════════════╝

  {id:"mu001",subj:"Multisystem / Mixed",bw:["Café-au-lait spots","Lisch nodules","Neurofibromas"],ans:"Neurofibromatosis Type 1",d:["NF2","Tuberous Sclerosis"],tp:"NF1: chromosome 17. >6 café-au-lait, Lisch nodules, optic glioma.",ww:{"NF2":"Bilateral acoustic schwannomas, chr 22.","Tuberous Sclerosis":"Ash-leaf spots, rhabdomyomas."}},
  {id:"mu002",subj:"Multisystem / Mixed",bw:["Marfan","Lens subluxation","Aortic root dilation"],ans:"Marfan Syndrome",d:["Ehlers-Danlos","Homocystinuria"],tp:"Marfan: fibrillin-1, AD. Upward lens subluxation. Aortic dissection risk is the primary cause of mortality.",ww:{"Ehlers-Danlos":"Hypermobile joints, not lens.","Homocystinuria":"Downward lens, thrombosis."}},
  {id:"mu003",subj:"Multisystem / Mixed",bw:["Ehlers-Danlos","Joint hypermobility","Skin hyperextensibility"],ans:"Ehlers-Danlos Syndrome",d:["Marfan Syndrome","Osteogenesis Imperfecta"],tp:"EDS: collagen defect. Vascular type (COL3A1): arterial/organ rupture risk.",ww:{"Marfan Syndrome":"Fibrillin-1, arachnodactyly.","Osteogenesis Imperfecta":"Brittle bones, blue sclerae."}},
  {id:"mu004",subj:"Multisystem / Mixed",bw:["Blue sclerae","Fractures","Hearing loss"],ans:"Osteogenesis Imperfecta",d:["Child Abuse","Rickets"],tp:"OI: type I collagen defect. Brittle bones, blue sclerae.",ww:{"Child Abuse":"Consider but OI is differential.","Rickets":"Vitamin D deficiency, bowing."}},
  {id:"mu005",subj:"Multisystem / Mixed",bw:["Down syndrome","Trisomy 21","Simian crease"],ans:"Down Syndrome",d:["Edwards Syndrome","Patau Syndrome"],tp:"Trisomy 21: AV canal defect, duodenal atresia, ALL risk.",ww:{"Edwards Syndrome":"Trisomy 18, rocker-bottom feet.","Patau Syndrome":"Trisomy 13, holoprosencephaly."}},
  {id:"mu006",subj:"Multisystem / Mixed",bw:["Turner syndrome","45,X","Short stature","Webbed neck"],ans:"Turner Syndrome",d:["Klinefelter","Noonan Syndrome"],tp:"Turner: coarctation, horseshoe kidney, streak gonads.",ww:{"Klinefelter":"47,XXY, tall, gynecomastia.","Noonan Syndrome":"Phenotypically similar, normal karyotype."}},
  {id:"mu007",subj:"Multisystem / Mixed",bw:["Klinefelter","47,XXY","Tall","Gynecomastia"],ans:"Klinefelter Syndrome",d:["Turner Syndrome","Kallmann Syndrome"],tp:"Klinefelter: small testes, infertility. Testosterone replacement.",ww:{"Turner Syndrome":"45,X, female, short.","Kallmann Syndrome":"Hypogonadism + anosmia."}},
  {id:"mu008",subj:"Multisystem / Mixed",bw:["Amyloidosis","Apple-green birefringence","Congo red"],ans:"Amyloidosis",d:["Multiple Myeloma","Sarcoidosis"],tp:"Amyloidosis: misfolded protein. AL (light chains) vs AA (chronic inflammation).",ww:{"Multiple Myeloma":"Can cause AL amyloid, separate entity.","Sarcoidosis":"Non-caseating granulomas."}},
  {id:"mu009",subj:"Multisystem / Mixed",bw:["Port-wine stain","Seizures","Glaucoma"],ans:"Sturge-Weber Syndrome",d:["NF1","Tuberous Sclerosis"],tp:"Sturge-Weber: leptomeningeal angioma, V1 port-wine stain. Tram-track calcifications.",ww:{"NF1":"Café-au-lait, neurofibromas.","Tuberous Sclerosis":"Ash-leaf spots."}},
  {id:"mu010",subj:"Multisystem / Mixed",bw:["VHL","Hemangioblastoma","Renal cell carcinoma"],ans:"Von Hippel-Lindau Syndrome",d:["NF2","Tuberous Sclerosis"],tp:"VHL: chromosome 3p. Clear cell RCC, hemangioblastomas, pheo.",ww:{"NF2":"Bilateral schwannomas.","Tuberous Sclerosis":"Angiomyolipomas (not RCC)."}},
  {id:"mu011",subj:"Multisystem / Mixed",bw:["Hemochromatosis","Bronze skin","Diabetes","Cirrhosis"],ans:"Hereditary Hemochromatosis",d:["Wilson Disease","Alcoholic Liver Disease"],tp:"HFE C282Y. Iron overload. Bronze diabetes. Phlebotomy treatment.",ww:{"Wilson Disease":"Copper, KF rings, young.","Alcoholic Liver Disease":"AST:ALT >2, drinking history."}},
  {id:"mu012",subj:"Multisystem / Mixed",bw:["Kayser-Fleischer rings","Liver disease","Tremor","Young"],ans:"Wilson Disease",d:["Hemochromatosis","Huntington"],tp:"Wilson: copper accumulation. Low ceruloplasmin. Penicillamine.",ww:{"Hemochromatosis":"Iron overload, bronze skin.","Huntington":"Chorea, older onset."}},
  {id:"mu013",subj:"Multisystem / Mixed",bw:["Fragile X","Large ears","Macroorchidism"],ans:"Fragile X Syndrome",d:["Down Syndrome","Autism"],tp:"CGG repeat, FMR1 gene. Most common inherited intellectual disability.",ww:{"Down Syndrome":"Trisomy 21, different features.","Autism":"No physical features."}},
  {id:"mu014",subj:"Multisystem / Mixed",bw:["Cystic fibrosis","Recurrent Pseudomonas","Pancreatic insufficiency"],ans:"Cystic Fibrosis",d:["Primary Ciliary Dyskinesia","Alpha-1 Antitrypsin"],tp:"CF: CFTR mutation chr 7. Chloride sweat test >60mEq/L diagnostic.",ww:{"Primary Ciliary Dyskinesia":"Situs inversus, Kartagener.","Alpha-1 Antitrypsin":"Basilar emphysema, liver."}},
  {id:"mu015",subj:"Multisystem / Mixed",bw:["Situs inversus","Bronchiectasis","Infertility"],ans:"Kartagener Syndrome",d:["Cystic Fibrosis","COPD"],tp:"Kartagener: primary ciliary dyskinesia. Dynein arm defect.",ww:{"Cystic Fibrosis":"CFTR mutation, no situs inversus.","COPD":"Smoking, no situs inversus."}},

];