/**
 * leaderboard.js — Global leaderboard + friends system for Buzzword Dash
 *
 * Uses Supabase (free tier) for persistent storage.
 * Loaded dynamically from CDN — no npm needed, works on GitHub Pages.
 *
 * SETUP: Run the SQL below in your Supabase SQL Editor, then replace
 * SUPABASE_URL and SUPABASE_ANON_KEY with your project values.
 *
 * ---------------------------------------------------------------
 * SQL to run in Supabase SQL Editor:
 * ---------------------------------------------------------------
 *
 * -- Leaderboard table
 * create table if not exists leaderboard (
 *   id bigint generated by default as identity primary key,
 *   player_id text not null,
 *   player_name text not null default 'Anonymous',
 *   avatar text default 'avatar_intern',
 *   score integer not null default 0,
 *   accuracy integer default 0,
 *   best_streak integer default 0,
 *   speed integer default 1,
 *   mode text default 'endless',
 *   badges text[] default '{}',
 *   created_at timestamp with time zone default timezone('utc', now())
 * );
 *
 * -- Friends table
 * create table if not exists friends (
 *   id bigint generated by default as identity primary key,
 *   player_id text not null,
 *   friend_id text not null,
 *   status text default 'pending',
 *   created_at timestamp with time zone default timezone('utc', now()),
 *   unique(player_id, friend_id)
 * );
 *
 * -- Player profiles (for friend lookups)
 * create table if not exists player_profiles (
 *   player_id text primary key,
 *   player_name text not null default 'Anonymous',
 *   avatar text default 'avatar_intern',
 *   badges text[] default '{}',
 *   best_score integer default 0,
 *   best_streak integer default 0,
 *   visible boolean default false,
 *   updated_at timestamp with time zone default timezone('utc', now())
 * );
 *
 * -- Match invites
 * create table if not exists match_invites (
 *   id bigint generated by default as identity primary key,
 *   from_player text not null,
 *   to_player text not null,
 *   room_code text not null,
 *   created_at timestamp with time zone default timezone('utc', now())
 * );
 *
 * -- Row Level Security
 * alter table leaderboard enable row level security;
 * alter table friends enable row level security;
 * alter table player_profiles enable row level security;
 * alter table match_invites enable row level security;
 *
 * create policy "Public read leaderboard" on leaderboard for select using (true);
 * create policy "Public insert leaderboard" on leaderboard for insert with check (true);
 *
 * create policy "Read own friends" on friends for select using (true);
 * create policy "Insert friends" on friends for insert with check (true);
 * create policy "Update own friends" on friends for update using (true);
 *
 * create policy "Public read profiles" on player_profiles for select using (visible = true);
 * create policy "Upsert own profile" on player_profiles for insert with check (true);
 * create policy "Update own profile" on player_profiles for update using (true);
 *
 * create policy "Read own invites" on match_invites for select using (true);
 * create policy "Insert invites" on match_invites for insert with check (true);
 * create policy "Delete own invites" on match_invites for delete using (true);
 *
 * ---------------------------------------------------------------
 */

// These are safe to expose publicly — Row Level Security handles authorization
var SUPABASE_URL = 'https://replaqmcwynrxclunkck.supabase.co';
var SUPABASE_ANON_KEY = 'sb_publishable_3k9K-AWsR3mARofiKqx0Ig_4TwvvbU-';

var PLAYER_ID_KEY = 'buzzword_dash_player_id';

var _supabaseClient = null;
var _playerId = null;
var _supabaseLoadPromise = null;

// ===== HELPER: Check if Supabase is configured =====

function isConfigured() {
    return SUPABASE_URL !== 'YOUR_SUPABASE_URL' && SUPABASE_ANON_KEY !== 'YOUR_SUPABASE_ANON_KEY';
}

// ===== HELPER: Load Supabase client from CDN =====

function loadSupabase() {
    if (_supabaseClient) return Promise.resolve(_supabaseClient);
    if (_supabaseLoadPromise) return _supabaseLoadPromise;

    _supabaseLoadPromise = new Promise(function (resolve, reject) {
        // Check if already loaded
        if (window.supabase && window.supabase.createClient) {
            _supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
            resolve(_supabaseClient);
            return;
        }

        var existing = document.querySelector('script[data-buzzword-supabase]');
        if (existing) {
            existing.addEventListener('load', function () {
                if (window.supabase && window.supabase.createClient) {
                    _supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
                    resolve(_supabaseClient);
                } else {
                    reject(new Error('Supabase loaded but createClient unavailable'));
                }
            });
            existing.addEventListener('error', function () {
                reject(new Error('Failed to load Supabase'));
            });
            return;
        }

        var script = document.createElement('script');
        script.src = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js';
        script.async = true;
        script.dataset.buzzwordSupabase = 'true';

        script.onload = function () {
            if (window.supabase && window.supabase.createClient) {
                _supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
                resolve(_supabaseClient);
            } else {
                reject(new Error('Supabase loaded but createClient unavailable'));
            }
        };

        script.onerror = function () {
            reject(new Error('Failed to load Supabase from CDN'));
        };

        document.head.appendChild(script);
    });

    return _supabaseLoadPromise;
}

// ===== HELPER: Get or create player ID =====

function getOrCreatePlayerId() {
    if (_playerId) return _playerId;

    try {
        _playerId = localStorage.getItem(PLAYER_ID_KEY);
    } catch (e) {
        // localStorage unavailable
    }

    if (!_playerId) {
        if (typeof crypto !== 'undefined' && crypto.randomUUID) {
            _playerId = crypto.randomUUID();
        } else {
            _playerId = 'player_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
        }
        try {
            localStorage.setItem(PLAYER_ID_KEY, _playerId);
        } catch (e) {
            // localStorage unavailable
        }
    }

    return _playerId;
}

// ===== AVATAR EMOJI MAP =====

var AVATAR_EMOJIS = {
    'avatar_intern': '🩺',
    'avatar_attending': '👨‍⚕️',
    'avatar_superhero': '🦸',
    'avatar_robot': '🤖',
    'avatar_wizard': '🧙',
    'avatar_zombie': '🧟',
    'avatar_golden': '🏆',
    'avatar_ambulance': '🚑',
    'avatar_racecar': '🏎️',
    'avatar_hearse': '⚰️',
    'avatar_nurse': '👩‍⚕️',
    'avatar_surgeon': '🔪',
    'avatar_skeleton': '💀'
};

function getAvatarEmoji(avatarId) {
    return AVATAR_EMOJIS[avatarId] || '🩺';
}

// ===== MODE DISPLAY =====

var MODE_LABELS = {
    'endless': '♾️ Endless',
    'daily': '📅 Daily',
    'study': '📖 Study',
    'weakness': '🎯 Weakness',
    'versus': '🎮 Versus',
    'mp_highscore': '⏱️ High Score',
    'mp_suddendeath': '💀 Sudden Death',
    'mp_race': '🏁 Race'
};

function getModeLabel(mode) {
    return MODE_LABELS[mode] || mode;
}

// ===== LEADERBOARD OBJECT =====

var leaderboard = {

    init: function () {
        if (!isConfigured()) {
            return Promise.resolve();
        }
        getOrCreatePlayerId();
        return loadSupabase().catch(function (e) {
            console.warn('Leaderboard: Supabase init failed:', e.message);
        });
    },

    getPlayerId: function () {
        return getOrCreatePlayerId();
    },

    submitScore: function (data) {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve();

        var playerId = getOrCreatePlayerId();

        var scoreInsert = _supabaseClient
            .from('leaderboard')
            .insert({
                player_id: playerId,
                player_name: data.playerName || 'Anonymous',
                avatar: data.avatar || 'avatar_intern',
                score: data.score || 0,
                accuracy: data.accuracy || 0,
                best_streak: data.bestStreak || 0,
                speed: data.speed || 1,
                mode: data.mode || 'endless',
                badges: data.badges || []
            });

        var profileUpsert = _supabaseClient
            .from('player_profiles')
            .upsert({
                player_id: playerId,
                player_name: data.playerName || 'Anonymous',
                avatar: data.avatar || 'avatar_intern',
                badges: data.badges || [],
                best_score: data.score || 0,
                best_streak: data.bestStreak || 0,
                visible: true,
                updated_at: new Date().toISOString()
            }, { onConflict: 'player_id' });

        return Promise.all([scoreInsert, profileUpsert]).catch(function (e) {
            console.warn('Leaderboard: submit failed:', e.message);
        });
    },

    getTopScores: function (mode, limit) {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve([]);

        var query = _supabaseClient
            .from('leaderboard')
            .select('*')
            .order('score', { ascending: false })
            .limit(limit || 50);

        if (mode) {
            query = query.eq('mode', mode);
        }

        return query.then(function (res) {
            return (res.data || []);
        }).catch(function (e) {
            console.warn('Leaderboard: getTopScores failed:', e.message);
            return [];
        });
    },

    getPlayerBest: function (mode) {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve(null);

        var playerId = getOrCreatePlayerId();
        var query = _supabaseClient
            .from('leaderboard')
            .select('*')
            .eq('player_id', playerId)
            .order('score', { ascending: false })
            .limit(1);

        if (mode) {
            query = query.eq('mode', mode);
        }

        return query.then(function (res) {
            return (res.data && res.data.length > 0) ? res.data[0] : null;
        }).catch(function (e) {
            console.warn('Leaderboard: getPlayerBest failed:', e.message);
            return null;
        });
    },

    searchPlayers: function (queryStr) {
        if (!isConfigured() || !_supabaseClient || !queryStr) return Promise.resolve([]);

        return _supabaseClient
            .from('player_profiles')
            .select('*')
            .eq('visible', true)
            .ilike('player_name', '%' + queryStr + '%')
            .limit(20)
            .then(function (res) {
                return (res.data || []);
            }).catch(function (e) {
                console.warn('Leaderboard: searchPlayers failed:', e.message);
                return [];
            });
    },

    sendFriendRequest: function (friendPlayerId) {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve();

        var playerId = getOrCreatePlayerId();
        return _supabaseClient
            .from('friends')
            .insert({
                player_id: playerId,
                friend_id: friendPlayerId,
                status: 'pending'
            }).catch(function (e) {
                console.warn('Leaderboard: sendFriendRequest failed:', e.message);
            });
    },

    acceptFriendRequest: function (requestId) {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve();

        return _supabaseClient
            .from('friends')
            .update({ status: 'accepted' })
            .eq('id', requestId)
            .catch(function (e) {
                console.warn('Leaderboard: acceptFriendRequest failed:', e.message);
            });
    },

    declineFriendRequest: function (requestId) {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve();

        return _supabaseClient
            .from('friends')
            .delete()
            .eq('id', requestId)
            .catch(function (e) {
                console.warn('Leaderboard: declineFriendRequest failed:', e.message);
            });
    },

    getFriends: function () {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve([]);

        var playerId = getOrCreatePlayerId();

        // Get friends where current player is either player_id or friend_id
        var q1 = _supabaseClient
            .from('friends')
            .select('*')
            .eq('player_id', playerId)
            .eq('status', 'accepted');

        var q2 = _supabaseClient
            .from('friends')
            .select('*')
            .eq('friend_id', playerId)
            .eq('status', 'accepted');

        return Promise.all([q1, q2]).then(function (results) {
            var friendIds = [];
            var rows1 = (results[0].data || []);
            var rows2 = (results[1].data || []);

            for (var i = 0; i < rows1.length; i++) {
                friendIds.push(rows1[i].friend_id);
            }
            for (var j = 0; j < rows2.length; j++) {
                friendIds.push(rows2[j].player_id);
            }

            if (friendIds.length === 0) return [];

            // Fetch profiles for friends
            return _supabaseClient
                .from('player_profiles')
                .select('*')
                .in('player_id', friendIds)
                .then(function (res) {
                    return (res.data || []);
                });
        }).catch(function (e) {
            console.warn('Leaderboard: getFriends failed:', e.message);
            return [];
        });
    },

    getPendingRequests: function () {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve([]);

        var playerId = getOrCreatePlayerId();
        return _supabaseClient
            .from('friends')
            .select('*')
            .eq('friend_id', playerId)
            .eq('status', 'pending')
            .order('created_at', { ascending: false })
            .then(function (res) {
                return (res.data || []);
            }).catch(function (e) {
                console.warn('Leaderboard: getPendingRequests failed:', e.message);
                return [];
            });
    },

    getFriendScores: function (mode, limit) {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve([]);

        var self = this;
        return self.getFriends().then(function (friends) {
            if (friends.length === 0) return [];

            var friendIds = friends.map(function (f) { return f.player_id; });
            // Include current player in friend leaderboard
            friendIds.push(getOrCreatePlayerId());

            var query = _supabaseClient
                .from('leaderboard')
                .select('*')
                .in('player_id', friendIds)
                .order('score', { ascending: false })
                .limit(limit || 50);

            if (mode) {
                query = query.eq('mode', mode);
            }

            return query.then(function (res) {
                return (res.data || []);
            });
        }).catch(function (e) {
            console.warn('Leaderboard: getFriendScores failed:', e.message);
            return [];
        });
    },

    inviteFriendToMatch: function (friendPlayerId, roomCode) {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve();

        var playerId = getOrCreatePlayerId();
        return _supabaseClient
            .from('match_invites')
            .insert({
                from_player: playerId,
                to_player: friendPlayerId,
                room_code: roomCode
            }).catch(function (e) {
                console.warn('Leaderboard: inviteFriendToMatch failed:', e.message);
            });
    },

    checkInvites: function () {
        if (!isConfigured() || !_supabaseClient) return Promise.resolve([]);

        var playerId = getOrCreatePlayerId();
        return _supabaseClient
            .from('match_invites')
            .select('*')
            .eq('to_player', playerId)
            .order('created_at', { ascending: false })
            .limit(5)
            .then(function (res) {
                var invites = res.data || [];
                // Delete read invites
                if (invites.length > 0) {
                    var ids = invites.map(function (inv) { return inv.id; });
                    _supabaseClient
                        .from('match_invites')
                        .delete()
                        .in('id', ids)
                        .catch(function () { /* ignore cleanup errors */ });
                }
                return invites;
            }).catch(function (e) {
                console.warn('Leaderboard: checkInvites failed:', e.message);
                return [];
            });
    },

    subscribeToInvites: function (callback) {
        if (!isConfigured() || !_supabaseClient) return null;

        var playerId = getOrCreatePlayerId();
        try {
            var channel = _supabaseClient
                .channel('match-invites-' + playerId)
                .on('postgres_changes', {
                    event: 'INSERT',
                    schema: 'public',
                    table: 'match_invites',
                    filter: 'to_player=eq.' + playerId
                }, function (payload) {
                    if (callback) callback(payload.new);
                })
                .subscribe();
            return channel;
        } catch (e) {
            console.warn('Leaderboard: subscribeToInvites failed:', e.message);
            return null;
        }
    }
};

// ===== RENDER LEADERBOARD SCREEN =====

function renderLeaderboardScreen() {
    if (!isConfigured()) {
        return '<div style="text-align:center;padding:40px 20px;color:var(--text-muted)">' +
            '<p style="font-size:48px;margin-bottom:12px">🏆</p>' +
            '<h3 style="color:var(--text-primary);margin-bottom:8px">Leaderboard Not Configured</h3>' +
            '<p style="font-size:12px;line-height:1.6">To enable the leaderboard, set up a free Supabase project and update the SUPABASE_URL and SUPABASE_ANON_KEY in <code>js/leaderboard.js</code>.</p>' +
            '<p style="font-size:11px;margin-top:12px;color:var(--text-muted)">See the SQL comments at the top of the file for table setup.</p>' +
            '</div>';
    }

    return '<div id="lbTabBar" style="display:flex;gap:4px;margin-bottom:12px">' +
        '<button class="btn btn-primary btn-sm lb-tab active" data-lb-tab="global" style="flex:1">🌍 Global</button>' +
        '<button class="btn btn-outline btn-sm lb-tab" data-lb-tab="friends" style="flex:1">👥 Friends</button>' +
        '<button class="btn btn-outline btn-sm lb-tab" data-lb-tab="mybest" style="flex:1">⭐ My Best</button>' +
        '</div>' +

        // Mode filter
        '<div style="margin-bottom:10px">' +
        '<select id="lbModeFilter" style="width:100%;padding:8px;border-radius:var(--radius-md);background:var(--bg-card);color:var(--text-primary);border:var(--border-card);font-size:12px">' +
        '<option value="">All Modes</option>' +
        '<option value="endless">♾️ Endless</option>' +
        '<option value="daily">📅 Daily</option>' +
        '<option value="study">📖 Study</option>' +
        '<option value="weakness">🎯 Weakness</option>' +
        '<option value="versus">🎮 Versus</option>' +
        '<option value="mp_highscore">⏱️ High Score</option>' +
        '<option value="mp_suddendeath">💀 Sudden Death</option>' +
        '<option value="mp_race">🏁 Race</option>' +
        '</select>' +
        '</div>' +

        // Score list
        '<div id="lbScoreList" style="min-height:100px">' +
        '<div style="text-align:center;padding:20px;color:var(--text-muted);font-size:12px">Loading...</div>' +
        '</div>' +

        // Friends section
        '<div id="lbFriendsSection" style="display:none;margin-top:16px">' +

        // Search players
        '<h4 style="font-size:13px;margin-bottom:6px;color:var(--text-secondary)">🔍 Find Players</h4>' +
        '<div style="display:flex;gap:6px;margin-bottom:10px">' +
        '<input type="text" id="lbSearchInput" placeholder="Search by name..." style="flex:1;padding:8px;border-radius:var(--radius-md);background:var(--bg-card);color:var(--text-primary);border:var(--border-card);font-size:12px">' +
        '<button class="btn btn-primary btn-sm" id="lbSearchBtn">Search</button>' +
        '</div>' +
        '<div id="lbSearchResults"></div>' +

        // Pending requests
        '<h4 style="font-size:13px;margin:12px 0 6px;color:var(--text-secondary)">📬 Pending Requests</h4>' +
        '<div id="lbPendingRequests" style="font-size:12px;color:var(--text-muted)">Loading...</div>' +

        // Friends list
        '<h4 style="font-size:13px;margin:12px 0 6px;color:var(--text-secondary)">👥 My Friends</h4>' +
        '<div id="lbFriendsList" style="font-size:12px;color:var(--text-muted)">Loading...</div>' +

        '</div>' +

        // Player ID for sharing
        '<div style="margin-top:16px;text-align:center;font-size:10px;color:var(--text-muted)">' +
        'Your Player ID: <code id="lbPlayerId" style="cursor:pointer;color:var(--accent-cyan)" title="Click to copy">' + getOrCreatePlayerId().substr(0, 8) + '...</code>' +
        '</div>';
}

// ===== RENDER SCORE LIST =====

function renderScoreEntries(entries, containerId) {
    var container = document.getElementById(containerId);
    if (!container) return;

    if (!entries || entries.length === 0) {
        container.innerHTML = '<div style="text-align:center;padding:20px;color:var(--text-muted);font-size:12px">No scores yet. Play a round to get on the board!</div>';
        return;
    }

    var html = '';
    var myId = getOrCreatePlayerId();

    for (var i = 0; i < entries.length; i++) {
        var entry = entries[i];
        var isMe = entry.player_id === myId;
        var rank = i + 1;
        var rankEmoji = rank === 1 ? '🥇' : rank === 2 ? '🥈' : rank === 3 ? '🥉' : '#' + rank;
        var avatarEmoji = getAvatarEmoji(entry.avatar);
        var modeLabel = getModeLabel(entry.mode);
        var borderColor = isMe ? 'var(--accent-cyan)' : 'var(--border-card)';
        var bgColor = isMe ? 'rgba(24,255,255,0.05)' : 'var(--bg-card)';

        html += '<div style="display:flex;align-items:center;gap:8px;padding:8px 10px;margin-bottom:4px;border-radius:var(--radius-md);background:' + bgColor + ';border:1px solid ' + borderColor + '">' +
            '<div style="font-size:14px;font-weight:800;width:32px;text-align:center;flex-shrink:0">' + rankEmoji + '</div>' +
            '<div style="font-size:20px;flex-shrink:0">' + avatarEmoji + '</div>' +
            '<div style="flex:1;min-width:0">' +
            '<div style="font-size:12px;font-weight:700;color:var(--text-primary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis">' + (entry.player_name || 'Anonymous') + (isMe ? ' (You)' : '') + '</div>' +
            '<div style="font-size:10px;color:var(--text-muted)">' + modeLabel + ' · ' + (entry.accuracy || 0) + '% · 🔥' + (entry.best_streak || 0) + '</div>' +
            '</div>' +
            '<div style="text-align:right;flex-shrink:0">' +
            '<div style="font-size:14px;font-weight:800;color:var(--accent-gold)">⭐ ' + (entry.score || 0) + '</div>' +
            '</div>' +
            '</div>';
    }

    container.innerHTML = html;
}

// ===== BIND LEADERBOARD EVENTS =====

function bindLeaderboardEvents(containerElement, storageModule) {
    if (!containerElement) return;

    var currentTab = 'global';
    var currentMode = '';

    // Tab switching
    var tabs = containerElement.querySelectorAll('.lb-tab');
    for (var t = 0; t < tabs.length; t++) {
        tabs[t].addEventListener('click', function () {
            var tab = this.dataset.lbTab;
            currentTab = tab;

            // Update tab styles
            var allTabs = containerElement.querySelectorAll('.lb-tab');
            for (var tt = 0; tt < allTabs.length; tt++) {
                allTabs[tt].className = 'btn btn-sm lb-tab ' + (allTabs[tt].dataset.lbTab === tab ? 'btn-primary active' : 'btn-outline');
            }

            // Show/hide friends section
            var friendsSection = document.getElementById('lbFriendsSection');
            if (friendsSection) {
                friendsSection.style.display = (tab === 'friends') ? 'block' : 'none';
            }

            refreshScores();
        });
    }

    // Mode filter
    var modeFilter = document.getElementById('lbModeFilter');
    if (modeFilter) {
        modeFilter.addEventListener('change', function () {
            currentMode = this.value;
            refreshScores();
        });
    }

    // Search
    var searchBtn = document.getElementById('lbSearchBtn');
    if (searchBtn) {
        searchBtn.addEventListener('click', function () {
            var input = document.getElementById('lbSearchInput');
            if (!input || !input.value.trim()) return;

            var resultsDiv = document.getElementById('lbSearchResults');
            if (resultsDiv) resultsDiv.innerHTML = '<div style="font-size:11px;color:var(--text-muted);padding:6px">Searching...</div>';

            leaderboard.searchPlayers(input.value.trim()).then(function (players) {
                if (!resultsDiv) return;
                if (players.length === 0) {
                    resultsDiv.innerHTML = '<div style="font-size:11px;color:var(--text-muted);padding:6px">No players found.</div>';
                    return;
                }

                var html = '';
                for (var p = 0; p < players.length; p++) {
                    var player = players[p];
                    html += '<div style="display:flex;align-items:center;gap:8px;padding:6px 8px;margin-bottom:3px;background:var(--bg-card);border-radius:var(--radius-md);border:var(--border-card)">' +
                        '<span style="font-size:16px">' + getAvatarEmoji(player.avatar) + '</span>' +
                        '<span style="flex:1;font-size:12px;font-weight:600">' + (player.player_name || 'Anonymous') + '</span>' +
                        '<span style="font-size:10px;color:var(--text-muted)">🏆' + (player.best_score || 0) + '</span>' +
                        '<button class="btn btn-outline btn-sm lb-add-friend" data-friend-id="' + player.player_id + '" style="font-size:10px;padding:2px 8px">+ Add</button>' +
                        '</div>';
                }
                resultsDiv.innerHTML = html;

                // Bind add friend buttons
                var addBtns = resultsDiv.querySelectorAll('.lb-add-friend');
                for (var a = 0; a < addBtns.length; a++) {
                    addBtns[a].addEventListener('click', function () {
                        var friendId = this.dataset.friendId;
                        var btn = this;
                        btn.disabled = true;
                        btn.textContent = '...';
                        leaderboard.sendFriendRequest(friendId).then(function () {
                            btn.textContent = '✓ Sent';
                            btn.style.color = 'var(--accent-green)';
                        }).catch(function () {
                            btn.textContent = '✗';
                            btn.disabled = false;
                        });
                    });
                }
            });
        });
    }

    // Copy player ID
    var playerIdEl = document.getElementById('lbPlayerId');
    if (playerIdEl) {
        playerIdEl.addEventListener('click', function () {
            var fullId = getOrCreatePlayerId();
            if (navigator.clipboard) {
                navigator.clipboard.writeText(fullId).then(function () {
                    playerIdEl.textContent = 'Copied!';
                    setTimeout(function () {
                        playerIdEl.textContent = fullId.substr(0, 8) + '...';
                    }, 2000);
                });
            }
        });
    }

    // Initial load
    refreshScores();
    loadFriendsData();

    function refreshScores() {
        var listEl = document.getElementById('lbScoreList');
        if (listEl) {
            listEl.innerHTML = '<div style="text-align:center;padding:20px;color:var(--text-muted);font-size:12px">Loading...</div>';
        }

        if (!isConfigured()) {
            if (listEl) listEl.innerHTML = '<div style="text-align:center;padding:20px;color:var(--text-muted);font-size:12px">Leaderboard not configured.</div>';
            return;
        }

        var mode = currentMode || null;

        if (currentTab === 'global') {
            leaderboard.getTopScores(mode, 50).then(function (scores) {
                renderScoreEntries(scores, 'lbScoreList');
            });
        } else if (currentTab === 'friends') {
            leaderboard.getFriendScores(mode, 50).then(function (scores) {
                renderScoreEntries(scores, 'lbScoreList');
            });
        } else if (currentTab === 'mybest') {
            // Show all of the player's own scores
            if (!_supabaseClient) {
                if (listEl) listEl.innerHTML = '<div style="text-align:center;padding:20px;color:var(--text-muted);font-size:12px">Not connected.</div>';
                return;
            }

            var playerId = getOrCreatePlayerId();
            var query = _supabaseClient
                .from('leaderboard')
                .select('*')
                .eq('player_id', playerId)
                .order('score', { ascending: false })
                .limit(50);

            if (mode) {
                query = query.eq('mode', mode);
            }

            query.then(function (res) {
                renderScoreEntries(res.data || [], 'lbScoreList');
            }).catch(function () {
                if (listEl) listEl.innerHTML = '<div style="text-align:center;padding:20px;color:var(--text-muted);font-size:12px">Failed to load scores.</div>';
            });
        }
    }

    function loadFriendsData() {
        if (!isConfigured()) return;

        // Load pending requests
        leaderboard.getPendingRequests().then(function (requests) {
            var pendingDiv = document.getElementById('lbPendingRequests');
            if (!pendingDiv) return;

            if (requests.length === 0) {
                pendingDiv.innerHTML = '<div style="font-size:11px;color:var(--text-muted)">No pending requests.</div>';
                return;
            }

            var html = '';
            for (var r = 0; r < requests.length; r++) {
                var req = requests[r];
                html += '<div style="display:flex;align-items:center;gap:6px;padding:6px 8px;margin-bottom:3px;background:var(--bg-card);border-radius:var(--radius-md);border:var(--border-card)">' +
                    '<span style="flex:1;font-size:11px">From: ' + req.player_id.substr(0, 8) + '...</span>' +
                    '<button class="btn btn-green btn-sm lb-accept-req" data-req-id="' + req.id + '" style="font-size:10px;padding:2px 6px">✓</button>' +
                    '<button class="btn btn-red btn-sm lb-decline-req" data-req-id="' + req.id + '" style="font-size:10px;padding:2px 6px">✗</button>' +
                    '</div>';
            }
            pendingDiv.innerHTML = html;

            // Bind accept/decline
            var acceptBtns = pendingDiv.querySelectorAll('.lb-accept-req');
            for (var a = 0; a < acceptBtns.length; a++) {
                acceptBtns[a].addEventListener('click', function () {
                    var reqId = this.dataset.reqId;
                    leaderboard.acceptFriendRequest(reqId).then(function () {
                        loadFriendsData();
                    });
                });
            }

            var declineBtns = pendingDiv.querySelectorAll('.lb-decline-req');
            for (var d = 0; d < declineBtns.length; d++) {
                declineBtns[d].addEventListener('click', function () {
                    var reqId = this.dataset.reqId;
                    leaderboard.declineFriendRequest(reqId).then(function () {
                        loadFriendsData();
                    });
                });
            }
        });

        // Load friends list
        leaderboard.getFriends().then(function (friends) {
            var friendsDiv = document.getElementById('lbFriendsList');
            if (!friendsDiv) return;

            if (friends.length === 0) {
                friendsDiv.innerHTML = '<div style="font-size:11px;color:var(--text-muted)">No friends yet. Search for players above!</div>';
                return;
            }

            var html = '';
            for (var f = 0; f < friends.length; f++) {
                var friend = friends[f];
                html += '<div style="display:flex;align-items:center;gap:8px;padding:6px 8px;margin-bottom:3px;background:var(--bg-card);border-radius:var(--radius-md);border:var(--border-card)">' +
                    '<span style="font-size:16px">' + getAvatarEmoji(friend.avatar) + '</span>' +
                    '<div style="flex:1">' +
                    '<div style="font-size:12px;font-weight:600">' + (friend.player_name || 'Anonymous') + '</div>' +
                    '<div style="font-size:10px;color:var(--text-muted)">🏆 ' + (friend.best_score || 0) + ' · 🔥 ' + (friend.best_streak || 0) + '</div>' +
                    '</div>' +
                    '<button class="btn btn-outline btn-sm lb-invite-friend" data-friend-id="' + friend.player_id + '" style="font-size:10px;padding:2px 6px">🎮 Invite</button>' +
                    '</div>';
            }
            friendsDiv.innerHTML = html;

            // Bind invite buttons
            var inviteBtns = friendsDiv.querySelectorAll('.lb-invite-friend');
            for (var ib = 0; ib < inviteBtns.length; ib++) {
                inviteBtns[ib].addEventListener('click', function () {
                    var friendId = this.dataset.friendId;
                    var roomCode = prompt('Enter a room code to invite your friend:');
                    if (roomCode && roomCode.trim().length > 0) {
                        leaderboard.inviteFriendToMatch(friendId, roomCode.trim().toUpperCase()).then(function () {
                            alert('Invite sent!');
                        }).catch(function () {
                            alert('Failed to send invite.');
                        });
                    }
                });
            }
        });
    }
}

// ===== EXPORTS =====

export { leaderboard, renderLeaderboardScreen, bindLeaderboardEvents };
